### ISSUE TITLE
Postinstall Not Working -  timed out after 30 seconds - Kernel.JSON

### ISSUE THREAD

**Issue by bbaileycyber** [CERT-Polska/drakvuf-sandbox#108]
I've not been able to get postinstall to work on either v.3 or v.4. It appears the datacollector python issue was resolved in .4 but I still can't get postinstall to work.

sudo draksetup postinstall
[sudo] password for aerospace:
[2020-05-11 15:50:49,994][INFO] Determined PDB GUID: 35a038b1f6e2e8caf642111e6ec66f571
[2020-05-11 15:50:49,995][INFO] Determined kernel filename: ntkrnlmp.pdb
[2020-05-11 15:50:49,995][INFO] Fetching PDB file...
[2020-05-11 15:50:50,000][DEBUG] Starting new HTTPS connection (1): msdl.microsoft.com:443
[2020-05-11 15:50:50,985][DEBUG] https://msdl.microsoft.com:443 "GET /download/symbols/ntkrnlmp.pdb/35a038b1f6e2e8caf642111e6ec66f571/ntkrnlmp.pdb HTTP/1.1" 302 0
[2020-05-11 15:50:50,987][DEBUG] Starting new HTTPS connection (1): vsblobprodscussu5shard71.blob.core.windows.net:443
[2020-05-11 15:50:51,846][DEBUG] https://vsblobprodscussu5shard71.blob.core.windows.net:443 "GET /b-4712e0edc5a240eabf23330d7df68e77/4BCE4A585EA137E74CBCBC6BD924F10104421CA13B3E07B2176D81B0A753824000.blob?sv=2017-04-17&sr=b&si=1&sig=ak92NJ9t6u1naH6Hi2ovweqjhfNGSRKxx18SyjzdhwM%3D&spr=https&se=2020-05-12T20%3A17%3A51Z&rscl=x-e2eid-11cdaa77-630a462e-9a29c39b-dd0fc8d8-session-e0c1b4a5-2d5744f8-b5548427-e1190f83 HTTP/1.1" 200 7711744
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7.71M/7.71M [00:07<00:00, 1.09MiB/s]
[2020-05-11 15:50:58,960][INFO] Generating profile out of PDB file...
[2020-05-11 15:51:10,831][INFO] Saving profile...
Traceback (most recent call last):
  File "/usr/bin/draksetup", line 7, in <module>
    ds.main()
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/draksetup.py", line 426, in main
    generate_profiles(args.no_report)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/draksetup.py", line 280, in generate_profiles
    output = subprocess.check_output(['vmi-win-offsets', 'name', 'vm-0', '-r', kernel_profile], timeout=30).decode('utf-8')
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 491, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1024, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1867, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/usr/lib/python3.8/subprocess.py", line 1068, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['vmi-win-offsets', 'name', 'vm-0', '-r', '/var/lib/drakrun/profiles/kernel.json']' timed out after 30 seconds

**Comment by icedevml** [comment]
@bbaileycyber I guess this is a Windows 10 guest?

We've already encountered this issue. I think this will be fixed soon.

**Comment by bbaileycyber** [comment]
Yes you are correct. I’ll try Windows 7 tomorrow and monitor for Win10 fix. Thanks!!

**Comment by icedevml** [comment]
related https://github.com/libvmi/libvmi/issues/897

**Comment by icedevml** [comment]
@bbaileycyber I think we've found all the nasty bugs that are sometimes preventing Win 10 from working properly with the sandbox.

I will post some pre-release of the fixed version here soon (approx. 1-2 days).

**Comment by icedevml** [comment]
@bbaileycyber Could you please test Windows 10 using this version of `drakvuf-bundle` as a replacement for the standard one?

https://debs.icedev.pl/minio/manual/patch20200516/

This build contains additional patches in both Xen and LibVMI.

Note that `*drakcore*` and `*drakrun*` packages should be the standard ones from:
https://github.com/CERT-Polska/drakvuf-sandbox/releases/tag/v0.4.0

Also please note that to maximize performance you might need to disable some Windows 10 background services before performing `drakrun postinstall`.

**Comment by trib0r3** [comment]
@icedevml your patch is working correctly - it fixes issue with Windows 10 :)

**Comment by icedevml** [comment]
@trib0r3 Great. Thanks for checking. We will release a new patched version soon.

**Comment by bbaileycyber** [comment]
apologies, but I was also able to confirm the patch fixed it on my install. I"ll upgrade to .5 now

**Comment by icedevml** [comment]
@bbaileycyber I've rolled back v0.5.0 because there was some mistake when building DEBs, the release should re-appear in a moment :)

Also, thanks for your confirmation.
