### ISSUE TITLE
Backend fails to create list analysis

### ISSUE THREAD

**Issue by BonusPlay** [CERT-Polska/drakvuf-sandbox#150]
`/list` endpoint crashes with 500.

```
[2020-06-22 12:25:16,290] ERROR in app: Exception on /list [GET]
Traceback (most recent call last):
  File "/opt/venvs/drakcore/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/venvs/drakcore/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/venvs/drakcore/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/venvs/drakcore/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/venvs/drakcore/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/venvs/drakcore/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/venvs/drakcore/lib/python3.7/site-packages/drakcore/app.py", line 45, in route_list
    "meta": json.loads(meta.read())})
AttributeError: 'dict' object has no attribute 'read'
```

**Comment by BonusPlay** [comment]
Related: #147. This is caused by `NoSuchKey` being caught, causing `meta = {}`. Sadly later we do `meta.read()` which fails.
