### ISSUE TITLE
Timeout when downloaing PDB in "darksetup postinstall" stage

### ISSUE THREAD

**Issue by liuya0904** [CERT-Polska/drakvuf-sandbox#228]
Hi,

I am testing your drakvuf sandbox in a Ubuntu 20.04 amd64 machine, but an issue was encountered in the postinstall stage as follows. It seems being caused by a timout when downloading PDB file.  Is there any way to solve or bypass it?  Thank you in advance.  The message is as follows:
liuya@jumper:~/drakvuf.0.8.0$ sudo draksetup postinstall
[2020-09-02 18:56:34,526][INFO] Determined PDB GUID: 684da42a30cc450f81c535b4d18944b12
[2020-09-02 18:56:34,527][INFO] Determined kernel filename: ntkrpamp.pdb
[2020-09-02 18:56:34,527][INFO] Fetching PDB file...
[2020-09-02 18:56:34,542][DEBUG] Starting new HTTPS connection (1): msdl.microsoft.com:443
 
 
 
msdl.microsoft.comTraceback (most recent call last):
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7ff64a72c2e0>: Failed to establish a new connection: [Errno 110] Connection timed out
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='msdl.microsoft.com', port=443): Max retries exceeded with url: /download/symbols/ntkrpamp.pdb/684da42a30cc450f81c535b4d18944b12/ntkrpamp.pdb (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff64a72c2e0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/usr/bin/draksetup", line 5, in <module>
    ds.main()
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/draksetup.py", line 417, in main
    generate_profiles(args.no_report, args.generate_usermode)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/draksetup.py", line 259, in generate_profiles
    dest = fetch_pdb(fn, pdb, destdir=os.path.join(LIB_DIR, 'profiles/'))
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/drakpdb.py", line 319, in fetch_pdb
    with requests.get(url, stream=True) as res:
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='msdl.microsoft.com', port=443): Max retries exceeded with url: /download/symbols/ntkrpamp.pdb/684da42a30cc450f81c535b4d18944b12/ntkrpamp.pdb (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff64a72c2e0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by chivay** [comment]
Hi,
it seems that the IP range hosting Microsoft symbol server is blocked by the Chinese Firewall (see https://github.com/MicrosoftDocs/feedback/issues/2310).
If you have access to a proxy, you can configure it with an environment variable as described here:
https://requests.readthedocs.io/en/master/user/advanced/#proxies

If you're running your own instance of symbol server, you can patch the URL in
`/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/drakpdb.py`
and we will add the option to override the symbol server in next release.

**Comment by liuya0904** [comment]
many thanks~
