### ISSUE TITLE
drakrun: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by icedevml** [CERT-Polska/drakvuf-sandbox#267]
The following entries appearing in journal after analysis:

```
paź 13 18:51:24 hostname drakrun[7314]: dnsmasq: exiting on receipt of SIGTERM
paź 13 18:51:24 hostname dnsmasq[3585]: exiting on receipt of SIGTERM
paź 13 18:51:24 hostname drakrun[7314]: [2020-10-13 18:51:24,189][INFO] waiting for tcpdump to exit
paź 13 18:51:24 hostname drakrun[7314]: WARNING:root:Failed to parse log entry:
paź 13 18:51:24 hostname drakrun[7314]: 'Method'
paź 13 18:51:24 hostname drakrun[7314]: WARNING:root:Failed to parse log entry:
paź 13 18:51:24 hostname drakrun[7314]: 'Method'
paź 13 18:51:24 hostname drakrun[7314]: WARNING:root:Failed to parse log entry:
paź 13 18:51:24 hostname drakrun[7314]: 'Method'
paź 13 18:51:24 hostname drakrun[7314]: WARNING:root:Failed to parse log entry:
paź 13 18:51:24 hostname drakrun[7314]: 'Method'
paź 13 18:51:24 hostname drakrun[7314]: WARNING:root:Failed to parse log entry:
paź 13 18:51:24 hostname drakrun[7314]: 'NoneType' object has no attribute 'replace'
paź 13 18:51:24 hostname drakrun[7314]: WARNING:root:Failed to parse log entry:
paź 13 18:51:24 hostname drakrun[7314]: 'NoneType' object has no attribute 'replace'
paź 13 18:51:24 hostname drakrun[7314]: WARNING:root:Failed to parse log entry:
paź 13 18:51:24 hostname drakrun[7314]: 'NoneType' object has no attribute 'replace'
paź 13 18:51:24 hostname drakrun[7314]: WARNING:root:Failed to parse log entry:
paź 13 18:51:24 hostname drakrun[7314]: 'NoneType' object has no attribute 'replace'
paź 13 18:51:24 hostname drakrun[7314]: WARNING:root:Failed to parse log entry:
paź 13 18:51:24 hostname drakrun[7314]: 'NoneType' object has no attribute 'replace'
paź 13 18:51:24 hostname drakrun[7314]: WARNING:root:Failed to parse log entry:
paź 13 18:51:24 hostname drakrun[7314]: 'Method'
paź 13 18:51:24 hostname drakrun[7314]: WARNING:root:Failed to parse log entry:
paź 13 18:51:24 hostname drakrun[7314]: 'NoneType' object has no attribute 'replace'
paź 13 18:51:24 hostname drakrun[7314]: WARNING:root:Failed to parse log entry:
paź 13 18:51:24 hostname drakrun[7314]: 'Method'
paź 13 18:51:24 hostname drakrun[7314]: WARNING:root:Failed to parse log entry:
paź 13 18:51:24 hostname drakrun[7314]: 'Method'
paź 13 18:51:24 hostname drakrun[7314]: WARNING:root:Failed to parse log entry:
paź 13 18:51:24 hostname drakrun[7314]: 'NoneType' object has no attribute 'replace'
paź 13 18:51:24 hostname drakrun[7314]: WARNING:root:Failed to parse log entry:
paź 13 18:51:24 hostname drakrun[7314]: 'NoneType' object has no attribute 'replace'
```

**Comment by icedevml** [comment]
```
paź 13 23:53:42 hostname drakrun[9337]: ERROR:root:BUG: Failed to parse log entry.
paź 13 23:53:42 hostname drakrun[9337]: {"Plugin":"regmon","TimeStamp":"1602625418.613792","PID":356,"PPID":340,"TID":1688,"UserName":"SessionID","UserId":1,"ProcessName":"\\Device\\HarddiskVolume2\\Windows\\System32\\csrss.exe","Method":"NtOpenKeyEx","Key":"\\REGISTRY\\MACHINE\\Software\\Microsoft\\Windows\\CurrentVersion\\SideBySide\\Winners","ValueName":null,"Value":null}
paź 13 23:53:42 hostname drakrun[9337]: Traceback (most recent call last):
paź 13 23:53:42 hostname drakrun[9337]:   File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/drakparse.py", line 178, in parse_logs
paź 13 23:53:42 hostname drakrun[9337]:     converted = str(plugin_obj(line_obj))
paź 13 23:53:42 hostname drakrun[9337]:   File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/drakparse.py", line 59, in __init__
paź 13 23:53:42 hostname drakrun[9337]:     detail = f"Type: REG_BINARY, Length: {len(obj['Value'].replace(' ', ''))}, Data: {obj['Value']}"
paź 13 23:53:42 hostname drakrun[9337]: AttributeError: 'NoneType' object has no attribute 'replace'
```
