### ISSUE TITLE
Exception handling of Keyboard Interrupt

### ISSUE THREAD

**Issue by manorit2001** [CERT-Polska/drakvuf-sandbox#451]
**Describe the bug**

Handling of Keyboard interrupt caused another exceptions

**How to reproduce**

1. Install drakcore and drakrun
2. Execute `sudo draksetup install winall.iso`
3. After installation, execute `sudo draksetup postinstall`
4. Interrupt during `fetch_pdb` in `create_rekall_profiles`

<details>
<summary>Traceback</summary>

```
[2021-02-27 23:57:01,066][INFO] Fetching rekall profile for Windows/Microsoft.NET/Framework/v4.0.30319/clr.dll
[2021-02-27 23:57:06,689][DEBUG] Starting new HTTPS connection (1): msdl.microsoft.com:443
[2021-02-27 23:57:07,141][DEBUG] https://msdl.microsoft.com:443 "GET /download/symbols/clr.pdb/d46e3e70b28d4183b6b09da7cdcb03d42/clr.pdb HTTP/1.1" 302 0
[2021-02-27 23:57:07,146][DEBUG] Starting new HTTPS connection (1): vsblobprodscussu5shard10.blob.core.windows.net:443
[2021-02-27 23:57:08,781][DEBUG] https://vsblobprodscussu5shard10.blob.core.windows.net:443 "GET /b-4712e0edc5a240eabf23330d7df68e77/80D7380313658BA7D72B98FC7F4C7CA4843C15396765195BDC38E69C683DE01200.blob?sv=2019-07-07&sr=b&si=1&sig=MOeKdHGKBkH%2FgpWQorSSEw1Th0da5GWUNCKhiKmcdd0%3D&spr=https&se=2021-02-28T18%3A30%3A13Z&rscl=x-e2eid-7b1013ad-81184d53-b78d1be9-1a3c8dc8-session-c978b591-ea924991-befca6ed-63bd8c08 HTTP/1.1" 200 19451904
 53%|█████████████████████████████████████████████████████████████████████████████▉                                                                     | 10.3M/19.5M [02:38<02:05, 73.1kiB/s] 53%|██████████████████████████████████████████████████████████████████████████████                                                                     | 10.3M/19.5M [02:38<02:20, 65.0kiB/s]
Traceback (most recent call last):
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/draksetup.py", line 245, in create_rekall_profiles
    tmp = fetch_pdb(guid["filename"], guid["GUID"], PROFILE_DIR)
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/drakpdb.py", line 327, in fetch_pdb
    for chunk in res.iter_content(chunk_size=1024 * 8):
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/lib/python3.7/http/client.py", line 457, in read
    n = self.readinto(b)
  File "/usr/lib/python3.7/http/client.py", line 501, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/draksetup", line 5, in <module>
    ds.main()
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/draksetup.py", line 390, in postinstall
    create_rekall_profiles(install_info)
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/draksetup.py", line 264, in create_rekall_profiles
    subprocess.check_output(f'umount {mnt_path_quoted}', shell=True)
  File "/usr/lib/python3.7/tempfile.py", line 944, in __exit__
    self.cleanup()
  File "/usr/lib/python3.7/tempfile.py", line 948, in cleanup
    _rmtree(self.name)
  File "/usr/lib/python3.7/shutil.py", line 491, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.7/shutil.py", line 429, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.7/shutil.py", line 429, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.7/shutil.py", line 449, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.7/shutil.py", line 447, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 30] Read-only file system: 'desktop.ini'
```

</details>

**Troubleshooting**:
- Trying `sudo draksetup postinstall` command again
  <details>
  <summary>Output</summary>
  
  ```
  user@debian:~/drakvuf-sandbox$ sudo draksetup postinstall
  /opt/venvs/drakrun/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!
    RequestsDependencyWarning)
  [2021-02-28 00:03:43,841][INFO] Ejecting installation CDs
  vm-0 is an invalid domain identifier (rc=-6)
  Traceback (most recent call last):
    File "/usr/bin/draksetup", line 5, in <module>
      ds.main()
    File "/opt/venvs/drakrun/lib/python3.7/site-packages/click/core.py", line 829, in __call__
      return self.main(*args, **kwargs)
    File "/opt/venvs/drakrun/lib/python3.7/site-packages/click/core.py", line 782, in main
      rv = self.invoke(ctx)
    File "/opt/venvs/drakrun/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/opt/venvs/drakrun/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/opt/venvs/drakrun/lib/python3.7/site-packages/click/core.py", line 610, in invoke
      return callback(*args, **kwargs)
    File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/draksetup.py", line 348, in postinstall
      eject_cd("vm-0", FIRST_CDROM_DRIVE)
    File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/draksetup.py", line 321, in eject_cd
      subprocess.run(["xl", "cd-eject", domain, drive], check=True)
    File "/usr/lib/python3.7/subprocess.py", line 487, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['xl', 'cd-eject', 'vm-0', 'hdc']' returned non-zero exit status 1.
  ```
  
  </details>

- Trying to load the saved snapshot of the xen VM caused errors
  <details>
  <summary>Output</summary>
  
  ```
  user@debian:~$ sudo xl restore /var/lib/drakrun/volumes/snapshot.sav
  Loading new save file /var/lib/drakrun/volumes/snapshot.sav (new xl fmt info 0x3/0x0/2031)
   Savefile contains xl domain config in JSON format
  Parsing config from <saved>
  xc: info: Found x86 HVM domain from Xen 4.14
  xc: info: Restoring domain
  xc: info: Restore successful
  xc: info: XenStore: mfn 0xfeffc, dom 0, evt 1
  xc: info: Console: mfn 0xfefff, dom 0, evt 2
  libxl: error: libxl_exec.c:403:spawn_watch_event: domain 7 device model: startup timed out
  libxl: error: libxl_dm.c:3103:device_model_spawn_outcome: Domain 7:domain 7 device model: spawn failed (rc=-9)
  libxl: error: libxl_dm.c:3319:device_model_postconfig_done: Domain 7:Post DM startup configs failed, rc=-9
  libxl: error: libxl_create.c:1832:domcreate_devmodel_started: Domain 7:device model did not start: -9
  libxl: error: libxl_domain.c:1182:libxl__destroy_domid: Domain 7:Non-existant domain
  libxl: error: libxl_domain.c:1136:domain_destroy_callback: Domain 7:Unable to destroy guest
  libxl: error: libxl_domain.c:1063:domain_destroy_cb: Domain 7:Destruction of domain failed
  ```
  
  </details>

- Looking at `mount` command, it seemed that the tmp directory which was created in `create_rekall_profiles` was still mounted
  <details>
  <summary>Output</summary>
  
  ```
  /dev/nbd0p2 on /tmp/tmpp9gzywzw type fuseblk (ro,relatime,user_id=0,group_id=0,allow_other,blksize=4096)
  user@debian:~/drakvuf-sandbox$ cd /tmp/tmpp9gzywzw/
  user@debian:/tmp/tmpp9gzywzw$ ls
  '$RECYCLE.BIN'             pagefile.sys    'Program Files (x86)'         Users
  'Documents and Settings'   ProgramData      Recovery                     Windows
   hiberfil.sys             'Program Files'  'System Volume Information'
  ```
  
  </details>
- Even after unmounting it and trying to load the saved snapshot as before, same `libxl` errors occurred
- After a reboot, trying the restore command again
  <details>
  <summary>Output</summary>
  
  ```
  user@debian:~$ sudo xl restore /var/lib/drakrun/volumes/snapshot.sav
  Loading new save file /var/lib/drakrun/volumes/snapshot.sav (new xl fmt info 0x3/0x0/2031)
   Savefile contains xl domain config in JSON format
  Parsing config from <saved>
  xc: info: Found x86 HVM domain from Xen 4.14
  xc: info: Restoring domain
  xc: info: Restore successful
  xc: info: XenStore: mfn 0xfeffc, dom 0, evt 1
  xc: info: Console: mfn 0xfefff, dom 0, evt 2
  libxl: error: libxl_exec.c:118:libxl_report_child_exitstatus: /etc/xen/scripts/vif-bridge online [861] exited with error status 1
  libxl: error: libxl_device.c:1259:device_hotplug_child_death_cb: script: Could not find bridge device drak0
  libxl: error: libxl_create.c:1858:domcreate_attach_devices: Domain 2:unable to add vif devices
  libxl: error: libxl_exec.c:118:libxl_report_child_exitstatus: /etc/xen/scripts/vif-bridge offline [898] exited with error status 1
  libxl: error: libxl_device.c:1259:device_hotplug_child_death_cb: script: Could not find bridge device drak0
  libxl: error: libxl_exec.c:118:libxl_report_child_exitstatus: /etc/xen/scripts/vif-bridge remove [923] exited with error status 1
  libxl: error: libxl_device.c:1259:device_hotplug_child_death_cb: script: Could not find bridge device drak0
  libxl: error: libxl_domain.c:1182:libxl__destroy_domid: Domain 2:Non-existant domain
  libxl: error: libxl_domain.c:1136:domain_destroy_callback: Domain 2:Unable to destroy guest
  libxl: error: libxl_domain.c:1063:domain_destroy_cb: Domain 2:Destruction of domain failed
  ```
  </details>

**Comment by manorit2001** [comment]
Looking at the docs now from [here](https://drakvuf-sandbox.readthedocs.io/en/latest/usage/troubleshooting.html), it seems like some Xen issue that caused the VM to not restore properly. But, the exception-handling part still remains on why the `unmount` didn't happen when it should have.

```
OSError: [Errno 30] Read-only file system: 'desktop.ini'
```

**Comment by icedevml** [comment]
I think the actual bug there is that we don't check if NTFS volume is already mounted when `draksetup` is ran. In such case, the `draksetup` should first perform cleanup and then mount everything again.

I think we would want to detect all the things that were left over after interrupted process rather than actually explicitly handle `KeyboardInterrupt`. This approach seems to be more robust to me. We already detect some circumstances, e.g. that `vm-0` is already running and needs to be shut down.

**Comment by manorit2001** [comment]
> I think the actual bug there is that we don't check if NTFS volume is already mounted when `draksetup` is ran. In such case, the `draksetup` should first perform cleanup and then mount everything again.
> 
> I think we would want to detect all the things that were left over after interrupted process rather than actually explicitly handle `KeyboardInterrupt`. This approach seems to be more robust to me. We already detect some circumstances, e.g. that `vm-0` is already running and needs to be shut down.

Yeah agreed, this sounds much better as this will be much more scalable and modular if some new cases arise.
