### ISSUE TITLE
drakplayground crash

### ISSUE THREAD

**Issue by manorit2001** [CERT-Polska/drakvuf-sandbox#455]
**Describe the bug**

`drakplayground` crashing due to `Error: Trying to create an image with the same filename as the backing file` with `qcow2` as storage backend

**How to reproduce**

1. Install drakcore and drakrun and setup them with `qcow2` storage pool
2. Execute `python3 drakplayground 0` as root

**qemu-version**
```
qemu-img version 3.1.0 (Debian 1:3.1+dfsg-8+deb10u8)
```
<details>
<summary>Traceback</summary>

```
(env) root@debian:/home/user/drakvuf-sandbox/drakrun/drakrun/py-scripts# python3 drakplayground 0
dnsmasq: started, version 2.80 DNS disabled
dnsmasq: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify dumpfile
dnsmasq-dhcp: DHCP, IP range 10.13.0.100 -- 10.13.0.200, lease time 12h
dnsmasq-dhcp: DHCP, sockets bound exclusively to interface drak0
qemu-img: /var/lib/drakrun/volumes/vm-0.img: Error: Trying to create an image with the same filename as the backing file
dnsmasq: exiting on receipt of SIGTERM
Traceback (most recent call last):
  File "drakplayground", line 5, in <module>
    playground.main()
  File "/home/user/drakvuf-sandbox/drakrun/drakrun/playground.py", line 98, in main
    DrakmonShell(args.vm_id, args.dns) as shell:
  File "/home/user/drakvuf-sandbox/drakrun/drakrun/playground.py", line 83, in __enter__
    self.vm.restore()
  File "/home/user/drakvuf-sandbox/drakrun/drakrun/vm.py", line 82, in restore
    self.backend.rollback_vm_storage(self.vm_id)
  File "/home/user/drakvuf-sandbox/drakrun/drakrun/storage.py", line 264, in rollback_vm_storage
    check=True,
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['qemu-img', 'create', '-f', 'qcow2', '-o', 'backing_file=/var/lib/drakrun/volumes/vm-0.img', '/var/lib/drakrun/volumes/vm-0.img']' returned non-zero exit status 1.

```

</details>

**possible error-prone lines**
when `vm_id` is `0`, that time the image name and the backing file name are same.
https://github.com/CERT-Polska/drakvuf-sandbox/blob/d87c8df6faca2d8a4fb45da919a396dd8718b3c0/drakrun/drakrun/storage.py#L246-L248

**Comment by icedevml** [comment]
@chi

**Comment by icedevml** [comment]
@chivay
