### ISSUE TITLE
libxl error: unable to add device with path [...]

### ISSUE THREAD

**Issue by kacpal** [CERT-Polska/drakvuf-sandbox#490]
**Describe the bug**

I am not able to install a machine because of libxl error during `xl create /etc/drakrun/configs/vm-0.cfg`.
Output of `sudo draksetup install windows_7.img`:
```
[2021-03-18 01:10:44,697][INFO] Checking xen-detect...
Running in PV context on Xen V4.14.
[2021-03-18 01:10:44,711][INFO] Testing if xl tool is sane...
[2021-03-18 01:10:44,738][INFO] Testing your Xen installation...
[2021-03-18 01:10:44,739][INFO] Checking if the test domain already exists...
test-hvm64-example is an invalid domain identifier (rc=-6)
[2021-03-18 01:10:44,753][INFO] Creating new test domain...
Parsing config from /tmp/tmpe5mv186_
[2021-03-18 01:10:44,879][INFO] Testing altp2m feature...
Succesfully enabled SLAT
[2021-03-18 01:10:44,889][INFO] Performing simple XTF test...
[2021-03-18 01:10:44,933][INFO] All tests passed. Your Xen installation seems to work properly.
[2021-03-18 01:10:44,933][INFO] Ensuring that drakrun@* services are stopped...
[2021-03-18 01:10:44,957][INFO] Performing installation...
[2021-03-18 01:10:44,957][INFO] Calculating hash of iso
262kit [00:00, 24.4Mit/s]                                                                                       
[2021-03-18 01:10:45,020][INFO] Generated VM configuration for vm-0
[2021-03-18 01:10:45,079][INFO] Bridge drak0 already exists.
[2021-03-18 01:10:45,090][INFO] Bridge drak0 is up
Parsing config from /etc/drakrun/configs/vm-0.cfg
libxl: error: libxl_device.c:1103:device_backend_callback: Domain 6:unable to add device with path /local/domain/0/backend/vif/6/0
libxl: error: libxl_create.c:1857:domcreate_attach_devices: Domain 6:unable to add vif devices
libxl: error: libxl_device.c:1103:device_backend_callback: Domain 6:unable to remove device with path /local/domain/0/backend/vif/6/0
libxl: error: libxl_domain.c:1529:devices_destroy_cb: Domain 6:libxl__devices_destroy failed
libxl: error: libxl_domain.c:1182:libxl__destroy_domid: Domain 6:Non-existant domain
libxl: error: libxl_domain.c:1136:domain_destroy_callback: Domain 6:Unable to destroy guest
libxl: error: libxl_domain.c:1063:domain_destroy_cb: Domain 6:Destruction of domain failed
[2021-03-18 01:11:05,701][ERROR] Failed to launch VM vm-0
Traceback (most recent call last):
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/draksetup.py", line 358, in install
    subprocess.run('xl create {}'.format(shlex.quote(cfg_path)), shell=True, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'xl create /etc/drakrun/configs/vm-0.cfg' returned non-zero exit status 3.
```
Logs from qemu:
```
VNC server running on 127.0.0.1:5900
qemu-system-i386: terminating on signal 1 from pid 6490 (xl)
qemu-system-i386: -usbdevice tablet: '-usbdevice' is deprecated, please use '-device usb-...' instead
VNC server running on :::5900
qemu-system-i386: terminating on signal 1 from pid 6524 (xl)
```
`xl create /etc/drakrun/configs/vm-0.cfg` produces exactly the same output:
```
Parsing config from /etc/drakrun/configs/vm-0.cfg
libxl: error: libxl_device.c:1103:device_backend_callback: Domain 11:unable to add device with path /local/domain/0/backend/vif/11/0
libxl: error: libxl_create.c:1857:domcreate_attach_devices: Domain 11:unable to add vif devices
libxl: error: libxl_device.c:1103:device_backend_callback: Domain 11:unable to remove device with path /local/domain/0/backend/vif/11/0
libxl: error: libxl_domain.c:1529:devices_destroy_cb: Domain 11:libxl__devices_destroy failed
libxl: error: libxl_domain.c:1182:libxl__destroy_domid: Domain 11:Non-existant domain
libxl: error: libxl_domain.c:1136:domain_destroy_callback: Domain 11:Unable to destroy guest
libxl: error: libxl_domain.c:1063:domain_destroy_cb: Domain 11:Destruction of domain failed
```

**How to reproduce**

The issue happens on fresh installation of Ubuntu 20.04.2. I've tried installing it on 2 separate desktops with the same results. I've been following exact instructions as described in the [documentation](https://drakvuf-sandbox.readthedocs.io/en/latest/usage/getting_started.html). Sandbox version: v0.15.0-p2.
Also, here's my `vm-0.cfg`:
```
# Autogenerated, don't edit this file directly!
# Instead please edit /etc/drakrun/scripts/cfg.template
# and restart drakrun@<vm_id> service.

# DomU config template for DRAKVUF Sandbox

# This is the template used to generate DomU configuration instances.
# Please don't edit this file unless you know what you are doing.

arch = 'x86_64'
name = "vm-0"
maxmem = 3072
memory = 3072
vcpus = 2
maxvcpus = 2
type = "hvm"
boot = "cd"
hap = 1
acpi = 1
on_poweroff = "destroy"
on_reboot = "restart"
on_crash = "destroy"
vnc=1
vnclisten="[::]:0,websocket=6400"
vncpasswd="ajx9ZLBQxsEoWoCUF1ni"
usb = 1
usbdevice = "tablet"
altp2m = 2
shadow_memory = 16
audio=1
soundhw='hda'
cpuid="host,htt=0"
vga="stdvga"
vif = [ 'type=ioemu,model=e1000,bridge=drak0' ]
disk = [ "tap:qcow2:/var/lib/drakrun/volumes/vm-0.img,xvda,w", "file:/home/kacper/Downloads/windows_7.img,hdc:cdrom,r" ]
vmtrace_buf_kb = 8192
```

**Comment by icedevml** [comment]
@kacpal Hello, thanks for reporting an issue and posting the detailed logs.

As DRAKVUF Sandbox is typically a server software, there might be problems when using desktop editions of Ubuntu/Debian as a host system. Could you please try with a headless system?

**Comment by icedevml** [comment]
I wonder if this bug is related to AppArmor or some other security hardening that is present on Ubuntu Focal Desktop by default.

**Comment by kacpal** [comment]
I can confirm that the server edition of Ubuntu showed the same error output. To make sure I am not doing anything wrong, I've succesfully installed the sandbox on Debian server - with the same drakvuf version and the same .iso.

**Comment by icedevml** [comment]
Ok, we will check what happened with Ubuntu Focal.

**Comment by MiS27** [comment]
I encounter similar problem and found out that it's related to kernel version:
https://lore.kernel.org/xen-devel/20210129005129.GA2452@mail-itl/T/#mceb9479875d3785c7ef969b690bcfb368bd2c266
Rollback to (install previous kernel version) temporary solves this issue.

**Comment by MiS27** [comment]
Here is corresponding  Ubuntu bug:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1920660

**Comment by MiS27** [comment]
FYI: As can be seen in launchpad fix is released for Focal. 
I tested Xen with 5.4.0-72-generic kernel and DomU starts fine.
