### ISSUE TITLE
Unstable sandbox launches

### ISSUE THREAD

**Issue by vornick** [CERT-Polska/drakvuf-sandbox#510]
Hello team, I've been installed the sandbox according to the manual on the site(Xen, Ubuntu 20.04 desktop ), setup by the guest system Win_Pro_10_20H2.2_64BIT_English. 

![image](https://user-images.githubusercontent.com/7591462/114713381-baf13a00-9d39-11eb-9829-9f4b16dd0589.png)

During the execution of the postinstall script, several "Warnings" was appeared:

`[2021-04-14 18:29:09,340][DEBUG] https://msdl.microsoft.com:443 "GET /download/symbols/win32k.pdb/ed706a38659240a066e6fb19b994baaa1/win32k.pdb HTTP/1.1" 302 0
[2021-04-14 18:29:09,341][DEBUG] Starting new HTTPS connection (1): vsblobprodscussu5shard53.blob.core.windows.net:443
[2021-04-14 18:29:10,206][DEBUG] https://vsblobprodscussu5shard53.blob.core.windows.net:443 "GET /b-4712e0edc5a240eabf23330d7df68e77/E2C937E04A267668F248EDDC6C0882FA7E1E6F644409F254AFCB22FF0811CF0200.blob?sv=2019-07-07&sr=b&si=1&sig=vLjoOIsq6aJvUpg4rPscw3X53pULV388pzje4l6xYSI%3D&spr=https&se=2021-04-15T07%3A53%3A07Z&rscl=x-e2eid-e5e1759e-4cee4d8d-aaec0a14-618e724b-session-ac7d88ae-205e4780-824aa3b1-2a802ffe HTTP/1.1" 200 936960
100%|███████████████████████████████████████| 937k/937k [00:00<00:00, 1.19MiB/s]
[2021-04-14 18:29:10,998][DEBUG] Parsing PDB into JSON profile...
[2021-04-14 18:29:11,804][WARNING] Unexpected exception while creating rekall profile for Windows/System32/win32k.sys, skipping...
Starting new HTTPS connection (1): vsblobprodscussu5shard57.blob.core.windows.net:443
[2021-04-14 18:29:40,582][DEBUG] https://vsblobprodscussu5shard57.blob.core.windows.net:443 "GET /b-4712e0edc5a240eabf23330d7df68e77/499F80023B01A2CDDEA2755843DBBBA7F01F3D8C2D11A5DA97632427F62B7BAC00.blob?sv=2019-07-07&sr=b&si=1&sig=fCsDR3dud%2Fn561i9oiiILshCH189rk48CuQjwoEPm3w%3D&spr=https&se=2021-04-15T08%3A17%3A14Z&rscl=x-e2eid-b2f0a887-240e4bc4-b6928e80-75e89039-session-ee87748e-4b154003-8255d7c0-43bfcb7e HTTP/1.1" 200 16953344
100%|█████████████████████████████████████| 17.0M/17.0M [00:09<00:00, 1.88MiB/s]
[2021-04-14 18:29:49,607][DEBUG] Parsing PDB into JSON profile...
[2021-04-14 18:30:04,216][WARNING] Unexpected exception while creating rekall profile for Windows/System32/ole32.dll, skipping...
[2021-04-14 18:30:04,218][INFO] Fetching rekall profile for Windows/SysWOW64/ole32.dll
[2021-04-14 18:30:04,887][DEBUG] Starting new HTTPS connection (1): msdl.microsoft.com:443
[2021-04-14 18:30:05,285][DEBUG] https://msdl.microsoft.com:443 "GET /download/symbols/ole32.pdb/6398f9ef78a48b97721109dc65204d271/ole32.pdb HTTP/1.1" 302 0
[2021-04-14 18:30:05,286][DEBUG] Starting new HTTPS connection (1): vsblobprodscussu5shard48.blob.core.windows.net:443
[2021-04-14 18:30:06,130][DEBUG] https://vsblobprodscussu5shard48.blob.core.windows.net:443 "GET /b-4712e0edc5a240eabf23330d7df68e77/01720396600F657BAF13B6BDF5F63DE064E103DE7025BDC02DE8F947C1DB82E100.blob?sv=2019-07-07&sr=b&si=1&sig=wdwd0ph93tnsuoICKOtePsuqxR05q49uQEp1NSoZ6uU%3D&spr=https&se=2021-04-15T08%3A00%3A20Z&rscl=x-e2eid-414b1522-33594149-b30836f7-cfac8e8c-session-f036fe9f-dfe0440f-b8c318a6-6723c7c1 HTTP/1.1" 200 17215488
100%|█████████████████████████████████████| 17.2M/17.2M [00:11<00:00, 1.52MiB/s]
[2021-04-14 18:30:17,479][DEBUG] Parsing PDB into JSON profile...
[2021-04-14 18:30:31,644][WARNING] Unexpected exception while creating rekall profile for Windows/SysWOW64/ole32.dll, skipping...
[2021-04-14 18:30:31,646][INFO] Fetching rekall profile for Windows/System32/combase.dll
[2021-04-14 18:30:32,395][DEBUG] Starting new HTTPS connection (1): msdl.microsoft.com:443
[2021-04-14 18:30:32,916][DEBUG] https://msdl.microsoft.com:443 "GET /download/symbols/combase.pdb/6e820961d4cb444b0486efd86e8e6c0c1/combase.pdb HTTP/1.1" 302 0
[2021-04-14 18:30:32,917][DEBUG] Starting new HTTPS connection (1): vsblobprodscussu5shard44.blob.core.windows.net:443
[2021-04-14 18:30:34,022][DEBUG] https://vsblobprodscussu5shard44.blob.core.windows.net:443 "GET /b-4712e0edc5a240eabf23330d7df68e77/60827125BB6EF446768628F05E69BED2B07BE43FE7A83B8FA4C79E9C1A92F23500.blob?sv=2019-07-07&sr=b&si=1&sig=mZp2zlCNQVjgYzYufaTMvOGvjmjSkGvuu3ahv47HG0U%3D&spr=https&se=2021-04-15T08%3A22%3A36Z&rscl=x-e2eid-f7ffb31b-311941e3-b5bb111a-76db2317-session-ac7da65d-205e4780-824aa3b1-2a802ffe HTTP/1.1" 200 91746304
100%|█████████████████████████████████████| 91.7M/91.7M [00:54<00:00, 1.68MiB/s]
[2021-04-14 18:31:28,671][DEBUG] Parsing PDB into JSON profile...
[2021-04-14 18:32:08,894][WARNING] Unexpected exception while creating rekall profile for Windows/System32/combase.dll, skipping...
[2021-04-14 18:32:08,898][INFO] Fetching rekall profile for Windows/Microsoft.NET/Framework/v4.0.30319/clr.dll
[2021-04-14 18:32:12,286][DEBUG] Starting new HTTPS connection (1): msdl.microsoft.com:443
[2021-04-14 18:32:12,756][DEBUG] https://msdl.microsoft.com:443 "GET /download/symbols/clr.pdb/835001bf0f9a419a917b167982ef86e12/clr.pdb HTTP/1.1" 302 0
[2021-04-14 18:32:12,757][DEBUG] Starting new HTTPS connection (1): vsblobprodscussu5shard13.blob.core.windows.net:443
[2021-04-14 18:32:13,630][DEBUG] https://vsblobprodscussu5shard13.blob.core.windows.net:443 "GET /b-4712e0edc5a240eabf23330d7df68e77/41B5372AC05B26D94E6B2E281F01355B612CC5228FE2DE2ED41B271F2E5312D000.blob?sv=2019-07-07&sr=b&si=1&sig=IGHy13cQvN4Qe25BciuRruR0LlgSMOc4gUAVxFwCPQM%3D&spr=https&se=2021-04-15T08%3A15%3A25Z&rscl=x-e2eid-9c1defcf-488e4919-bf4b74fa-17d7f145-session-ac7c419e-205e4780-824aa3b1-2a802ffe HTTP/1.1" 200 19008512
100%|█████████████████████████████████████| 19.0M/19.0M [00:11<00:00, 1.72MiB/s]
[2021-04-14 18:32:24,700][DEBUG] Parsing PDB into JSON profile...
[2021-04-14 18:32:48,525][INFO] Fetching rekall profile for Windows/Microsoft.NET/Framework/v2.0.50727/mscorwks.dll
[2021-04-14 18:32:48,525][WARNING] Failed to copy file Windows/Microsoft.NET/Framework/v2.0.50727/mscorwks.dll, skipping...
[2021-04-14 18:32:49,071][INFO] All right, drakrun setup is done.
[2021-04-14 18:32:49,072][INFO] First instance of drakrun will be enabled automatically...
[2021-04-14 18:32:49,736][INFO] If you want to have more parallel instances, execute:
[2021-04-14 18:32:49,736][INFO]   # draksetup scale <number of instances>`

I did not attach any importance to this, since most of the functions were loaded. But during the test run, I saw oddities. The first file (sample Lab 03-03.exe from book "practical malware analysis") was loaded and successfully analyzed:
![image](https://user-images.githubusercontent.com/7591462/114711899-29cd9380-9d38-11eb-9678-79187d33b8f4.png)

But when i load another samples, i see an error:
`
апр 14 19:13:14 test-FWA-3270 drakrun[18646]:   File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/main.py", line 460, in analyze_sample
апр 14 19:13:14 test-FWA-3270 drakrun[18646]:     subprocess.run(
апр 14 19:13:14 test-FWA-3270 drakrun[18646]:   File "/usr/lib/python3.8/subprocess.py", line 512, in run
апр 14 19:13:14 test-FWA-3270 drakrun[18646]:     raise CalledProcessError(retcode, process.args,
апр 14 19:13:14 test-FWA-3270 drakrun[18646]: subprocess.CalledProcessError: Command '['drakvuf', '-a', 'memdump', '-a', 'apimon', '-a', 'syscalls', '-a', 'tlsmon', '-a', 'procmon', '-o', 'json', '-F', '-j', '5', '-t', '240', '-i', '5320', '-k', '0x1aa002', '-d', 'vm-1', '--dll-hooks-list', '/tmp/drakrun/vm-1/hooks.txt', '--memdump-dir', '/tmp/drakrun/vm-1/output/dumps', '-r', '/var/lib/drakrun/profiles/kernel.json', '-e', 'C:\\Users\\jack\\Desktop\\OrderConfirmation.exe', '-c', 'C:\\Users\\jack\\Desktop', '--json-wow', '/var/lib/drakrun/profiles/wow_ntdll_profile.json', '--json-tcpip', '/var/lib/drakrun/profiles/tcpip_profile.json', '--json-sspicli', '/var/lib/drakrun/profiles/sspicli_profile.json', '--json-kernel32', '/var/lib/drakrun/profiles/kernel32_profile.json', '--json-kernelbase', '/var/lib/drakrun/profiles/kernelbase_profile.json', '--json-wow-kernel32', '/var/lib/drakrun/profiles/wow_kernel32_profile.json', '--json-iphlpapi', '/var/lib/drakrun/profiles/iphlpapi_profile.json', '--json-mpr', '/var/lib/drakrun/profiles/mpr_profile.json', '--json-ntdll', '/var/lib/drakrun/profiles/ntdll_profile.json', '--json-clr', '/var/lib/drakrun/profiles/clr_profile.json']' returned non-zero exit status 4.
апр 14 19:13:14 test-FWA-3270 drakrun[18646]: [2021-04-14 19:13:14,274][ERROR] Giving up after 3 failures...
апр 14 19:13:14 test-FWA-3270 drakrun[18646]: ERROR:karton.drakrun-prod:Giving up after 3 failures...
апр 14 19:13:14 test-FWA-3270 drakrun[18646]: [2021-04-14 19:13:14,282][INFO] Task done - c40cf4ee-cb17-41fe-b7f2-5eaeaf218f95
апр 14 19:13:14 test-FWA-3270 drakrun[18646]: INFO:karton.drakrun-prod:Task done - c40cf4ee-cb17-41fe-b7f2-5eaeaf218f95`

I am just starting to explore the sandbox and don't know what the problem is this. Maybe guest system or host system are not supported. Maybe a hardware problem... Can you help me? 
P.s. I have not found answers to typical errors, everything is in the issue on github. Is it possible to write a step-to-reproduce to find the causes of errors? For example "these errors in the postinstall script mean that the problem is in the guest system, try this OS version number"
[journal.txt](https://github.com/CERT-Polska/drakvuf-sandbox/files/6310961/journal.txt)
[log_install.txt](https://github.com/CERT-Polska/drakvuf-sandbox/files/6310964/log_install.txt)

**Comment by icedevml** [comment]
Hi, thanks for reporting.

```
апр 12 16:17:36 test-FWA-3270 drakrun[19811]: [2021-04-12 16:17:36,678][ERROR] Analysis attempt failed. Retrying...
апр 12 16:17:36 test-FWA-3270 drakrun[19811]: Traceback (most recent call last):
апр 12 16:17:36 test-FWA-3270 drakrun[19811]:   File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/main.py", line 552, in process
апр 12 16:17:36 test-FWA-3270 drakrun[19811]:     info = self.analyze_sample(sample_path, workdir, outdir, start_command, timeout)
апр 12 16:17:36 test-FWA-3270 drakrun[19811]:   File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/main.py", line 436, in analyze_sample
апр 12 16:17:36 test-FWA-3270 drakrun[19811]:     injected_fn = json.loads(result.stdout)['ProcessName']
апр 12 16:17:36 test-FWA-3270 drakrun[19811]:   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
апр 12 16:17:36 test-FWA-3270 drakrun[19811]:     return _default_decoder.decode(s)
апр 12 16:17:36 test-FWA-3270 drakrun[19811]:   File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
апр 12 16:17:36 test-FWA-3270 drakrun[19811]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
апр 12 16:17:36 test-FWA-3270 drakrun[19811]:   File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
апр 12 16:17:36 test-FWA-3270 drakrun[19811]:     obj, end = self.scan_once(s, idx)
апр 12 16:17:36 test-FWA-3270 drakrun[19811]: json.decoder.JSONDecodeError: Invalid \escape: line 1 column 104 (char 103)
апр 12 16:17:36 test-FWA-3270 drakrun[19811]: ERROR:karton.drakrun-prod:Analysis attempt failed. Retrying...
апр 12 16:17:36 test-FWA-3270 drakrun[19811]: Traceback (most recent call last):
апр 12 16:17:36 test-FWA-3270 drakrun[19811]:   File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/main.py", line 552, in process
апр 12 16:17:36 test-FWA-3270 drakrun[19811]:     info = self.analyze_sample(sample_path, workdir, outdir, start_command, timeout)
апр 12 16:17:36 test-FWA-3270 drakrun[19811]:   File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/main.py", line 436, in analyze_sample
апр 12 16:17:36 test-FWA-3270 drakrun[19811]:     injected_fn = json.loads(result.stdout)['ProcessName']
апр 12 16:17:36 test-FWA-3270 drakrun[19811]:   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
апр 12 16:17:36 test-FWA-3270 drakrun[19811]:     return _default_decoder.decode(s)
апр 12 16:17:36 test-FWA-3270 drakrun[19811]:   File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
апр 12 16:17:36 test-FWA-3270 drakrun[19811]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
апр 12 16:17:36 test-FWA-3270 drakrun[19811]:   File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
апр 12 16:17:36 test-FWA-3270 drakrun[19811]:     obj, end = self.scan_once(s, idx)
апр 12 16:17:36 test-FWA-3270 drakrun[19811]: json.decoder.JSONDecodeError: Invalid \escape: line 1 column 104 (char 103)
```

this is interesting

and here the log level is not enough to tell what actually happened

```
апр 14 00:45:46 test-FWA-3270 drakrun[783]:     raise CalledProcessError(retcode, process.args,
апр 14 00:45:46 test-FWA-3270 drakrun[783]: subprocess.CalledProcessError: Command '['drakvuf', '-a', 'tlsmon', '-a', 'procmon', '-a', 'syscalls', '-a', 'memdump', '-a', 'apimon', '-o', 'json', '-F', '-j', '5', '-t', '180', '-i', '3996', '-k', '0x1aa002', '-d', 'vm-1', '--dll-hooks-list', '/tmp/drakrun/vm-1/hooks.txt', '--memdump-dir', '/tmp/drakrun/vm-1/output/dumps', '-r', '/var/lib/drakrun/profiles/kernel.json', '-e', 'C:\\Users\\jack\\Desktop\\cromeBdoor.exe', '-c', 'C:\\Users\\jack\\Desktop', '--json-wow', '/var/lib/drakrun/profiles/wow_ntdll_profile.json', '--json-tcpip', '/var/lib/drakrun/profiles/tcpip_profile.json', '--json-sspicli', '/var/lib/drakrun/profiles/sspicli_profile.json', '--json-kernel32', '/var/lib/drakrun/profiles/kernel32_profile.json', '--json-kernelbase', '/var/lib/drakrun/profiles/kernelbase_profile.json', '--json-wow-kernel32', '/var/lib/drakrun/profiles/wow_kernel32_profile.json', '--json-iphlpapi', '/var/lib/drakrun/profiles/iphlpapi_profile.json', '--json-mpr', '/var/lib/drakrun/profiles/mpr_profile.json', '--json-ntdll', '/var/lib/drakrun/profiles/ntdll_profile.json', '--json-clr', '/var/lib/drakrun/profiles/clr_profile.json']' returned non-zero exit status 4.
```

I will dig this deeper

**Comment by icedevml** [comment]
Btw. we haven't really tested Windows 10 20H2, could you try with build 2004 in the meantime? It's confirmed to work stable, so if the bugs would repeat then it would be a strong indication that we've broken something in the newer sandbox versions.

**Comment by vornick** [comment]
Oh, thanks for the quick response. I didn’t mention that the analysis also failed on builds 1909 and 1709, I thought that these were very old builds and found a newer one. I can reproduce a case from 1909 if necessary for research.

**Comment by icedevml** [comment]
@vornick Ok, important question. Does this fail consistently just for a particular sample and particular other samples work fine all the time?

**Comment by icedevml** [comment]
Generally, exit code would mean "injection succeeded but the process didn't work for some reason (bad architecture, missing DLLs, etc)". The problem is that we don't handle it gracefully. Maybe some .NET or vc redist is missing on the VM?

**Comment by vornick** [comment]
No, only lab03-03.exe worked on version 20H2. All other samples crashes. I reinstalled win 1909, install vc redist and verified that .NET is installed. As a result, I could not run the analysis on any sample. Its all time crashed.
1909 upload sample logs:
`{"levelname": "INFO", "created": 1618449327.1573687, "message": "Running on: test-FWA-3270"}
{"levelname": "INFO", "created": 1618449327.1606183, "message": "Sample SHA256: ae8a1c7eb64c42ea2a04f97523ebf0844c27029eb040d910048b680f884b9dce"}
{"levelname": "INFO", "created": 1618449327.1610956, "message": "Analysis UID: 748e474c-6090-4727-b0de-8869b1692c82"}
{"levelname": "INFO", "created": 1618449327.1617954, "message": "Running file as exe"}
{"levelname": "INFO", "created": 1618449327.1623535, "message": "Using file name Lab03-03.exe"}
{"levelname": "INFO", "created": 1618449327.16727, "message": "Start command: %f"}
{"levelname": "INFO", "created": 1618449327.1699514, "message": "Trying to analyze sample (attempt 1/3)"}
{"levelname": "INFO", "created": 1618449332.3590288, "message": "VM restored"}
{"levelname": "INFO", "created": 1618449332.4405704, "message": "Copying sample to VM..."}
{"levelname": "INFO", "created": 1618449333.3941615, "message": "Using command: C:\\Users\\jack\\Desktop\\Lab03-03.exe"}
{"levelname": "ERROR", "created": 1618449336.8335202, "message": "Analysis attempt failed. Retrying..."}
{"levelname": "INFO", "created": 1618449336.8392544, "message": "Trying to analyze sample (attempt 2/3)"}
{"levelname": "INFO", "created": 1618449341.9697611, "message": "VM restored"}
{"levelname": "INFO", "created": 1618449342.0578077, "message": "Copying sample to VM..."}
{"levelname": "INFO", "created": 1618449342.7899506, "message": "Using command: C:\\Users\\jack\\Desktop\\Lab03-03.exe"}
{"levelname": "ERROR", "created": 1618449346.2004392, "message": "Analysis attempt failed. Retrying..."}
{"levelname": "INFO", "created": 1618449346.207517, "message": "Trying to analyze sample (attempt 3/3)"}
{"levelname": "INFO", "created": 1618449351.4127579, "message": "VM restored"}
{"levelname": "INFO", "created": 1618449351.509797, "message": "Copying sample to VM..."}
{"levelname": "INFO", "created": 1618449352.3253806, "message": "Using command: C:\\Users\\jack\\Desktop\\Lab03-03.exe"}
{"levelname": "ERROR", "created": 1618449355.757905, "message": "Analysis attempt failed. Retrying..."}
{"levelname": "ERROR", "created": 1618449355.7613904, "message": "Giving up after 3 failures..."}`

And here are the samples that I analyzed
https://app.any.run/tasks/cccee6f8-dba2-4dd5-803a-771139c65540/#
https://app.any.run/tasks/c7d603e1-762c-4576-99e9-5b460438c0a9/
I also ran samples created by the msfvenom
For example:
`msfvenom -f exe -p windows / exec CMD = "powershell -nop -exec Bypass systeminfo" -o malware.exe`

[log_postinstall.txt](https://github.com/CERT-Polska/drakvuf-sandbox/files/6312796/log_postinstall.txt)
[journal_1909.txt](https://github.com/CERT-Polska/drakvuf-sandbox/files/6312797/journal_1909.txt)

**Comment by icedevml** [comment]
Could you send me these samples at monk@cert.pl ? Please make some zip archive and give the password `infected` when sending an attachment. This would be very helpful for me when trying to reproduce.

It's very weird that the sandbox behaves so bad on your side, I will try to investigate this as much as possible.

**Comment by vornick** [comment]
I sent you an email with samples, tomorrow I will try to check the work of version 2004.

**Comment by vornick** [comment]
```
A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  monk@cert.pl
    retry timeout exceeded
```

Here is an archive with samples https://disk.yandex.ru/d/R81pIOJtFj5j7w

**Comment by icedevml** [comment]
I can confirm this is reproducible for latest master and Windows 20H2. This is probably some regression.

This has some racey nature, if I would introduce `time.sleep(5)` between `injector` and `drakvuf` then everything works ok

**Comment by icedevml** [comment]
Enclosed logs from the debug session where it was reproduced with debugging enabled

[logz.txt](https://github.com/CERT-Polska/drakvuf-sandbox/files/6320628/logz.txt)

**Comment by icedevml** [comment]
I think Windows 10 (especially more recent builds) is really burdened with background processes and this causes that injection timeout of 5 seconds is simply not enough

@vornick

Please check this workaround:
```
sed -i 's/"-j", "5",/"-j", "60",/' /opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/main.py
systemctl restart drakrun@1
```

it will dirty-patch `drakrun` service so it will use injection timeout of 60 seconds instead of the default 5 seconds. Could you confirm if the sandbox works better with such workaround?

**Comment by vornick** [comment]
No changes for me. The error is similar. 
[journalctl.txt](https://github.com/CERT-Polska/drakvuf-sandbox/files/6335113/journalctl.txt)

**Comment by vornick** [comment]
Update, now i run drakvof on ubuntu 18.04 last release deb version. In Windows 7 all samples run and analyses correctly. Win 10 2004 still unstable.
