### ISSUE TITLE
Support Xen 4.15

### ISSUE THREAD

**Issue by vornick** [CERT-Polska/drakvuf-sandbox#515]
I decided to reinstall the system on ubuntu 18.04 server. Installed Xen from the site https://github.com/tklengyel/drakvuf and did not notice that there was Xen 4.15.

After draksetup test i see this:
```
[2021-04-16 10:12:42,346][INFO] Checking xen-detect...
Running in PV context on Xen V4.14.
[2021-04-16 10:12:42,359][INFO] Testing if xl tool is sane...
[2021-04-16 10:12:42,391][INFO] Testing your Xen installation...
[2021-04-16 10:12:42,392][INFO] Checking if the test domain already exists...
test-hvm64-example is an invalid domain identifier (rc=-6)
[2021-04-16 10:12:42,407][INFO] Creating new test domain...
Parsing config from /tmp/tmptrt1a9sy
libxl: error: libxl_create.c:676:libxl__domain_make: domain creation fail: Permission denied
libxl: error: libxl_create.c:1238:initiate_domain_create: cannot make domain: -3
Traceback (most recent call last):
  File "/usr/bin/draksetup", line 5, in <module>
    ds.main()
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/draksetup.py", line 223, in test
    if not sanity_check():
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/draksetup.py", line 166, in sanity_check
    if not perform_xtf():
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/draksetup.py", line 190, in perform_xtf
    subprocess.run(f'xl create -p {tmpf.name}', shell=True, stderr=subprocess.STDOUT, timeout=30, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'xl create -p /tmp/tmptrt1a9sy' returned non-zero exit status 3
```
Do you plan to support xen 4.15?

**Comment by icedevml** [comment]
Please don't mix Xen installed from source and DRAKVUF Sandbox debs. The next Sandbox release will be shipped with Xen 4.15, but the current one is targeting 4.14 and using any other version is not supported.

**Comment by icedevml** [comment]
wontfix
