### ISSUE TITLE
drak-web service throws error after upgard to 0.16

### ISSUE THREAD

**Issue by Latanyor** [CERT-Polska/drakvuf-sandbox#538]
After upgrading to 0.16 the dark-web service throws an error as soon as I access the Webpage.

Error:
```
May 05 15:56:36 milano uwsgi[1130]: *** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
May 05 15:56:36 milano uwsgi[1130]: python threads support enabled
May 05 15:56:36 milano uwsgi[1130]: your server socket listen backlog is limited to 100 connections
May 05 15:56:36 milano uwsgi[1130]: your mercy for graceful operations on workers is 60 seconds
May 05 15:56:36 milano uwsgi[1130]: mapped 364520 bytes (355 KB) for 4 cores
May 05 15:56:36 milano uwsgi[1130]: *** Operational MODE: preforking ***
May 05 15:56:38 milano uwsgi[1130]: Traceback (most recent call last):
May 05 15:56:38 milano uwsgi[1130]:   File "/opt/venvs/drakcore/lib/python3.7/site-packages/drakcore/app.py", line 25, in <module>
May 05 15:56:38 milano uwsgi[1130]:     backend = SystemService(conf).backend
May 05 15:56:38 milano uwsgi[1130]:   File "/opt/venvs/drakcore/lib/python3.7/site-packages/karton/system/system.py", line 27, in __init__
May 05 15:56:38 milano uwsgi[1130]:     super(SystemService, self).__init__(config=config)
May 05 15:56:38 milano uwsgi[1130]:   File "/opt/venvs/drakcore/lib/python3.7/site-packages/karton/core/base.py", line 106, in __init__
May 05 15:56:38 milano uwsgi[1130]:     super().__init__(config=config, identity=identity, backend=backend)
May 05 15:56:38 milano uwsgi[1130]:   File "/opt/venvs/drakcore/lib/python3.7/site-packages/karton/core/base.py", line 28, in __init__
May 05 15:56:38 milano uwsgi[1130]:     self.backend = backend or KartonBackend(self.config)
May 05 15:56:38 milano uwsgi[1130]:   File "/opt/venvs/drakcore/lib/python3.7/site-packages/karton/core/backend.py", line 37, in __init__
May 05 15:56:38 milano uwsgi[1130]:     self.redis = self.make_redis(config)
May 05 15:56:38 milano uwsgi[1130]:   File "/opt/venvs/drakcore/lib/python3.7/site-packages/karton/core/backend.py", line 60, in make_redis
May 05 15:56:38 milano uwsgi[1130]:     redis.ping()
May 05 15:56:38 milano uwsgi[1130]:   File "/opt/venvs/drakcore/lib/python3.7/site-packages/redis/client.py", line 1378, in ping
May 05 15:56:38 milano uwsgi[1130]:     return self.execute_command('PING')
May 05 15:56:38 milano uwsgi[1130]:   File "/opt/venvs/drakcore/lib/python3.7/site-packages/redis/client.py", line 901, in execute_command
May 05 15:56:38 milano uwsgi[1130]:     return self.parse_response(conn, command_name, **options)
May 05 15:56:38 milano uwsgi[1130]:   File "/opt/venvs/drakcore/lib/python3.7/site-packages/redis/client.py", line 915, in parse_response
May 05 15:56:38 milano uwsgi[1130]:     response = connection.read_response()
May 05 15:56:38 milano uwsgi[1130]:   File "/opt/venvs/drakcore/lib/python3.7/site-packages/redis/connection.py", line 739, in read_response
May 05 15:56:38 milano uwsgi[1130]:     response = self._parser.read_response()
May 05 15:56:38 milano uwsgi[1130]:   File "/opt/venvs/drakcore/lib/python3.7/site-packages/redis/connection.py", line 340, in read_response
May 05 15:56:38 milano uwsgi[1130]:     raise error
May 05 15:56:38 milano uwsgi[1130]: redis.exceptions.BusyLoadingError: Redis is loading the dataset in memory
May 05 15:56:38 milano uwsgi[1130]: unable to load app 0 (mountpoint='') (callable not found or import error)
May 05 15:56:38 milano uwsgi[1130]: *** no app loaded. going in full dynamic mode ***
May 05 15:56:38 milano uwsgi[1130]: uWSGI running as root, you can use --uid/--gid/--chroot options
May 05 15:56:38 milano uwsgi[1130]: *** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
May 05 15:56:38 milano uwsgi[1130]: *** uWSGI is running in multiple interpreter mode ***
May 05 15:56:38 milano uwsgi[1130]: spawned uWSGI master process (pid: 1130)
May 05 15:56:38 milano uwsgi[1130]: spawned uWSGI worker 1 (pid: 1235, cores: 1)
May 05 15:56:38 milano uwsgi[1130]: spawned uWSGI worker 2 (pid: 1236, cores: 1)
May 05 15:56:38 milano uwsgi[1130]: spawned uWSGI worker 3 (pid: 1237, cores: 1)
May 05 15:56:38 milano uwsgi[1130]: spawned uWSGI worker 4 (pid: 1238, cores: 1)
May 05 15:56:38 milano uwsgi[1130]: spawned uWSGI http 1 (pid: 1239)
May 05 15:57:27 milano uwsgi[1130]: --- no python application found, check your startup logs for errors ---
May 05 15:57:27 milano uwsgi[1130]: [pid: 1238|app: -1|req: -1/1] 10.0.46.64 () {42 vars in 645 bytes} [Wed May  5 15:57:27 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
May 05 15:57:29 milano uwsgi[1130]: --- no python application found, check your startup logs for errors ---
May 05 15:57:29 milano uwsgi[1130]: [pid: 1237|app: -1|req: -1/2] 10.0.46.64 () {42 vars in 645 bytes} [Wed May  5 15:57:29 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
```

`drak-healtchcheck` still shows all services running:
```
Checking daemon status...
drak-web.service              OK
drak-system.service           OK
drak-minio.service            OK
Checking worker status...
drakrun@1.service             OK
drak-postprocess@1.service    OK
```

The Webpage only shows an `Internal Server Error`.

**Comment by Latanyor** [comment]
`drak-system` shows the same error:

```
-- Logs begin at Wed 2021-05-05 16:07:04 CEST, end at Wed 2021-05-05 16:22:19 CEST. --
May 05 16:07:11 milano systemd[1]: Started drak-system service.
May 05 16:07:15 milano drak-system[1127]: Traceback (most recent call last):
May 05 16:07:15 milano drak-system[1127]:   File "/opt/venvs/drakcore/bin/drak-system", line 4, in <module>
May 05 16:07:15 milano drak-system[1127]:     main()
May 05 16:07:15 milano drak-system[1127]:   File "/opt/venvs/drakcore/lib/python3.7/site-packages/drakcore/system.py", line 24, in main
May 05 16:07:15 milano drak-system[1127]:     service = SystemService(config)
May 05 16:07:15 milano drak-system[1127]:   File "/opt/venvs/drakcore/lib/python3.7/site-packages/karton/system/system.py", line 27, in __init__
May 05 16:07:15 milano drak-system[1127]:     super(SystemService, self).__init__(config=config)
May 05 16:07:15 milano drak-system[1127]:   File "/opt/venvs/drakcore/lib/python3.7/site-packages/karton/core/base.py", line 106, in __init__
May 05 16:07:15 milano drak-system[1127]:     super().__init__(config=config, identity=identity, backend=backend)
May 05 16:07:15 milano drak-system[1127]:   File "/opt/venvs/drakcore/lib/python3.7/site-packages/karton/core/base.py", line 28, in __init__
May 05 16:07:15 milano drak-system[1127]:     self.backend = backend or KartonBackend(self.config)
May 05 16:07:15 milano drak-system[1127]:   File "/opt/venvs/drakcore/lib/python3.7/site-packages/karton/core/backend.py", line 37, in __init__
May 05 16:07:15 milano drak-system[1127]:     self.redis = self.make_redis(config)
May 05 16:07:15 milano drak-system[1127]:   File "/opt/venvs/drakcore/lib/python3.7/site-packages/karton/core/backend.py", line 60, in make_redis
May 05 16:07:15 milano drak-system[1127]:     redis.ping()
May 05 16:07:15 milano drak-system[1127]:   File "/opt/venvs/drakcore/lib/python3.7/site-packages/redis/client.py", line 1378, in ping
May 05 16:07:15 milano drak-system[1127]:     return self.execute_command('PING')
May 05 16:07:15 milano drak-system[1127]:   File "/opt/venvs/drakcore/lib/python3.7/site-packages/redis/client.py", line 901, in execute_command
May 05 16:07:15 milano drak-system[1127]:     return self.parse_response(conn, command_name, **options)
May 05 16:07:15 milano drak-system[1127]:   File "/opt/venvs/drakcore/lib/python3.7/site-packages/redis/client.py", line 915, in parse_response
May 05 16:07:15 milano drak-system[1127]:     response = connection.read_response()
May 05 16:07:15 milano drak-system[1127]:   File "/opt/venvs/drakcore/lib/python3.7/site-packages/redis/connection.py", line 739, in read_response
May 05 16:07:15 milano drak-system[1127]:     response = self._parser.read_response()
May 05 16:07:15 milano drak-system[1127]:   File "/opt/venvs/drakcore/lib/python3.7/site-packages/redis/connection.py", line 340, in read_response
May 05 16:07:15 milano drak-system[1127]:     raise error
May 05 16:07:15 milano drak-system[1127]: redis.exceptions.BusyLoadingError: Redis is loading the dataset in memory
May 05 16:07:15 milano systemd[1]: drak-system.service: Main process exited, code=exited, status=1/FAILURE
May 05 16:07:15 milano systemd[1]: drak-system.service: Failed with result 'exit-code'.
May 05 16:07:20 milano systemd[1]: drak-system.service: Service RestartSec=5s expired, scheduling restart.
May 05 16:07:20 milano systemd[1]: drak-system.service: Scheduled restart job, restart counter is at 1.
May 05 16:07:20 milano systemd[1]: Stopped drak-system service.
May 05 16:07:20 milano systemd[1]: Started drak-system service.
May 05 16:07:20 milano drak-system[1262]: [2021-05-05 16:07:20,563][INFO] Verifying bucket existence...
May 05 16:07:20 milano drak-system[1262]: /opt/venvs/drakcore/lib/python3.7/site-packages/karton/core/logger.py:59: UserWarning: There is no active log consumer to receive logged messages.
May 05 16:07:20 milano drak-system[1262]:   warnings.warn("There is no active log consumer to receive logged messages.")
May 05 16:07:20 milano drak-system[1262]: [2021-05-05 16:07:20,583][INFO] Manager karton.system started
```

**Comment by icedevml** [comment]
This is some problem with your Redis instance in general. Have you tried to just restart `redis-server` or reboot the machine? Please also check `redis-server` logs in order to find out whether there is something useful there.

I belive the root issue here is Redis.

**Comment by Latanyor** [comment]
I tried restarting the machine sevaral times, yes. Didn't help.
 Will look into the redis-server logs 👍🏻

**Comment by chivay** [comment]
I'm not sure but this looks like a race during startup - both Redis and our services are started at the same time by systemd and Redis isn't fast enough to load everything.
As you can see
```
May 05 16:07:20 milano systemd[1]: Stopped drak-system service.
May 05 16:07:20 milano systemd[1]: Started drak-system service.
May 05 16:07:20 milano drak-system[1262]: [2021-05-05 16:07:20,563][INFO] Verifying bucket existence...
```
just a few second after the crash everything's working correctly

**Comment by Latanyor** [comment]
Restarting the specific services in order did fix the issue.

Did this months ago and forgot to close. 
Doing that now. Sorry and thanks
