### ISSUE TITLE
draksetup test fail after upgrading to v0.16.0

### ISSUE THREAD

**Issue by manorit2001** [CERT-Polska/drakvuf-sandbox#539]
**Describe the bug**

`draksetup test` started failing after upgrade to v0.16.0. Downgrading back to v0.15.0-p2 makes it work but upgrading it breaks it again

**How to reproduce**

Steps to reproduce the behavior: (debian buster specific)
1. Install drakvuf bundle provided with v0.16.0
<details>
<summary>Some warnings related to no version information</summary>

```
Running in PV context on Xen V4.14.                                                                                                                                                           
xl: /usr/local/lib/libxenstore.so.3.0: no version information available (required by /lib/libxenlight.so.4.15)                                                                               
xl: /usr/local/lib/libxenstore.so.3.0: no version information available (required by /lib/libxenlight.so.4.15)                                                                               
------------------------------------------

Resources dedicated to Dom0 (host system):
-> CPU core(s): 2
-> Memory: 1024 MB

------------------------------------------
You can edit these settings in /etc/default/grub.d/xen.cfg
WARNING: GRUB_DEFAULT changed to boot into Xen by default!
         Edit /etc/default/grub.d/xen.cfg to avoid this warning.
Generating grub configuration file ...
Found background image: /usr/share/images/desktop-base/desktop-grub.png
Found linux image: /boot/vmlinuz-4.19.0-14-amd64
Found initrd image: /boot/initrd.img-4.19.0-14-amd64
dpkg: warning: version '/boot/xen.gz' has bad syntax: version number does not start with digit
Found linux image: /boot/vmlinuz-4.19.0-14-amd64
Found initrd image: /boot/initrd.img-4.19.0-14-amd64
Found linux image: /boot/vmlinuz-4.19.0-14-amd64
Found initrd image: /boot/initrd.img-4.19.0-14-amd64
Found linux image: /boot/vmlinuz-4.19.0-14-amd64
Found initrd image: /boot/initrd.img-4.19.0-14-amd64
Found linux image: /boot/vmlinuz-4.19.0-14-amd64
Found initrd image: /boot/initrd.img-4.19.0-14-amd64
Found linux image: /boot/vmlinuz-4.19.0-14-amd64
Found initrd image: /boot/initrd.img-4.19.0-14-amd64
done
add xenfs to /etc/fstab
Running in PV context on Xen V4.14.
Detected system is running on Xen, checking EPT support in xl dmesg...
xl: /usr/local/lib/libxenstore.so.3.0: no version information available (required by /lib/libxenlight.so.4.15)
```
</details>

2. Reboot
3. Install `drakcore` and `drakrun` v0.16.0 (reboot/no reboot)
4. run `draksetup test`

<details>
<summary>Logs</summary>

```
user@debian:~$ sudo draksetup test
[sudo] password for user: 
[2021-05-06 20:49:04,335][INFO] Checking xen-detect...
Running in PV context on Xen V4.15.
[2021-05-06 20:49:04,396][INFO] Testing if xl tool is sane...
[2021-05-06 20:49:04,479][INFO] Testing your Xen installation...
[2021-05-06 20:49:04,509][INFO] Checking if the test domain already exists...
test-hvm64-example is an invalid domain identifier (rc=-6)
[2021-05-06 20:49:04,578][INFO] Creating new test domain...
Parsing config from /tmp/tmpgvcpo7_s
libxl: error: libxl_create.c:671:libxl__domain_make: domain creation fail: Permission denied
libxl: error: libxl_create.c:1233:initiate_domain_create: cannot make domain: -3
Traceback (most recent call last):
  File "/usr/bin/draksetup", line 5, in <module>
    ds.main()
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/draksetup.py", line 242, in test
    if not sanity_check():
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/draksetup.py", line 185, in sanity_check
    if not perform_xtf():
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/draksetup.py", line 209, in perform_xtf
    subprocess.run(f'xl create -p {tmpf.name}', shell=True, stderr=subprocess.STDOUT, timeout=30, check=True)
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'xl create -p /tmp/tmpgvcpo7_s' returned non-zero exit status 3.
```

</details>

**Output of the [status checking commands](https://github.com/CERT-Polska/drakvuf-sandbox#checking-service-status)**

If applicable (optional).
**drak-healthcheck**
```
Checking daemon status...
drak-web.service              OK
drak-system.service           OK
drak-minio.service            OK
Checking worker status...
drakrun@1.service             ERROR
drak-postprocess@1.service    OK

```

**journalctl -e -u drakrun@1**
```
May 06 20:53:01 debian systemd[1]: drakrun@1.service: Main process exited, code=exited, status=1/FAILURE
May 06 20:53:01 debian systemd[1]: drakrun@1.service: Failed with result 'exit-code'.
May 06 20:53:06 debian systemd[1]: drakrun@1.service: Service RestartSec=5s expired, scheduling restart.
May 06 20:53:06 debian systemd[1]: drakrun@1.service: Scheduled restart job, restart counter is at 41.
May 06 20:53:06 debian systemd[1]: Stopped drakrun service.
May 06 20:53:06 debian systemd[1]: Started drakrun service.
May 06 20:53:06 debian drakrun[1266]: Traceback (most recent call last):
May 06 20:53:06 debian drakrun[1266]:   File "/opt/venvs/drakrun/bin/drakrun", line 5, in <module>
May 06 20:53:06 debian drakrun[1266]:     dm.cmdline_main()
May 06 20:53:06 debian drakrun[1266]:   File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/main.py", line 713, in cmdline_main
May 06 20:53:06 debian drakrun[1266]:     main(args)
May 06 20:53:06 debian drakrun[1266]:   File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/main.py", line 757, in main
May 06 20:53:06 debian drakrun[1266]:     c = DrakrunKarton(conf, args.instance)
May 06 20:53:06 debian drakrun[1266]:   File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/main.py", line 144, in __init__
May 06 20:53:06 debian drakrun[1266]:     self.install_info = InstallInfo.load()
May 06 20:53:06 debian drakrun[1266]:   File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/config.py", line 36, in load
May 06 20:53:06 debian drakrun[1266]:     with open(InstallInfo._INSTALL_FILE_PATH, "r") as f:
May 06 20:53:06 debian drakrun[1266]: FileNotFoundError: [Errno 2] No such file or directory: '/etc/drakrun/install.json'
May 06 20:53:06 debian systemd[1]: drakrun@1.service: Main process exited, code=exited, status=1/FAILURE
May 06 20:53:06 debian systemd[1]: drakrun@1.service: Failed with result 'exit-code'.
May 06 20:53:11 debian systemd[1]: drakrun@1.service: Service RestartSec=5s expired, scheduling restart.
May 06 20:53:11 debian systemd[1]: drakrun@1.service: Scheduled restart job, restart counter is at 42.
May 06 20:53:11 debian systemd[1]: Stopped drakrun service.
May 06 20:53:11 debian systemd[1]: Started drakrun service.
May 06 20:53:12 debian drakrun[1272]: Traceback (most recent call last):
May 06 20:53:12 debian drakrun[1272]:   File "/opt/venvs/drakrun/bin/drakrun", line 5, in <module>
May 06 20:53:12 debian drakrun[1272]:     dm.cmdline_main()
May 06 20:53:12 debian drakrun[1272]:   File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/main.py", line 713, in cmdline_main
May 06 20:53:12 debian drakrun[1272]:     main(args)
May 06 20:53:12 debian drakrun[1272]:   File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/main.py", line 757, in main
May 06 20:53:12 debian drakrun[1272]:     c = DrakrunKarton(conf, args.instance)
May 06 20:53:12 debian drakrun[1272]:   File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/main.py", line 144, in __init__
May 06 20:53:12 debian drakrun[1272]:     self.install_info = InstallInfo.load()
May 06 20:53:12 debian drakrun[1272]:   File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/config.py", line 36, in load
May 06 20:53:12 debian drakrun[1272]:     with open(InstallInfo._INSTALL_FILE_PATH, "r") as f:
May 06 20:53:12 debian drakrun[1272]: FileNotFoundError: [Errno 2] No such file or directory: '/etc/drakrun/install.json'
May 06 20:53:12 debian systemd[1]: drakrun@1.service: Main process exited, code=exited, status=1/FAILURE
May 06 20:53:12 debian systemd[1]: drakrun@1.service: Failed with result 'exit-code'.

```

**qemu test-hvm64-example logs**

```
root@debian:/var/log/xen# cat qemu-dm-test-hvm64-example.log.*
VNC server running on 127.0.0.1:5900
qemu-system-i386: terminating on signal 1 from pid 1051 (xl)
VNC server running on 127.0.0.1:5900
qemu-system-i386: terminating on signal 1 from pid 23923 (xl)
VNC server running on 127.0.0.1:5901
qemu-system-i386: terminating on signal 1 from pid 4959 (xl)
VNC server running on 127.0.0.1:5901
qemu-system-i386: terminating on signal 1 from pid 4615 (xl)
VNC server running on 127.0.0.1:5901
qemu-system-i386: terminating on signal 1 from pid 4546 (xl)
VNC server running on 127.0.0.1:5900
qemu-system-i386: terminating on signal 1 from pid 4207 (xl)
VNC server running on 127.0.0.1:5900
qemu-system-i386: terminating on signal 1 from pid 3518 (xl)
VNC server running on 127.0.0.1:5900
qemu-system-i386: terminating on signal 1 from pid 3335 (xl)
VNC server running on 127.0.0.1:5900
qemu-system-i386: terminating on signal 1 from pid 27267 (xl)
VNC server running on 127.0.0.1:5900
qemu-system-i386: terminating on signal 1 from pid 27233 (xl)

```

**Comment by icedevml** [comment]
Could you show your `/etc/drakrun/scripts/cfg.template`?

**Comment by icedevml** [comment]
If you have `vmtrace_*` options in the config, could you comment them out and check if it starts working?

**Comment by manorit2001** [comment]
It is already commented 
```
root@debian:/var/log/xen# cat /etc/drakrun/scripts/cfg.template
# DomU config template for DRAKVUF Sandbox

# This is the template used to generate DomU configuration instances.
# Please don't edit this file unless you know what you are doing.

arch = 'x86_64'
name = "vm-{{ VM_ID }}"
maxmem = 2548
memory = 2548
vcpus = 2
maxvcpus = 2
type = "hvm"
boot = "cd"
hap = 1
acpi = 1
on_poweroff = "destroy"
on_reboot = "destroy"
on_crash = "destroy"
vnc=1
vnclisten="[::]:{{ VM_ID }},websocket={{ VNC_PORT }}"
vncpasswd="Xyfk3mmrVJwGYwEaufx1"
usb = 1
usbdevice = "tablet"
altp2m = 2
shadow_memory = 16
audio=1
soundhw='hda'
cpuid="host,htt=0"
vga="stdvga"
vif = [ 'type=ioemu,model=e1000,bridge=drak{{ VM_ID }}' ]
disk = [ {{ DISKS }} ]
# uncomment when using IPT
# vmtrace_buf_kb = 8192

```

**Comment by icedevml** [comment]
```
xl: /usr/local/lib/libxenstore.so.3.0: no version information available (required by /lib/libxenlight.so.4.15)                                                                               
xl: /usr/local/lib/libxenstore.so.3.0: no version information available (required by /lib/libxenlight.so.4.15)    
```

this looks bad 🤔

**Comment by icedevml** [comment]
@manorit2001 Seems like you have an old local Xen installation in `/usr/local` and this conflicts with the new binary version from `drakvuf-bundle`. Please remove xen-related stuff from `/usr/local/lib` and `/usr/local/bin`.

**Comment by manorit2001** [comment]
> @manorit2001 Seems like you have an old local Xen installation in `/usr/local` and this conflicts with the new binary version from `drakvuf-bundle`. Please remove xen-related stuff from `/usr/local/lib` and `/usr/local/bin`.

Hi, seems right

I removed all the `xen` related stuff ( also from `/usr/local/sbin` ) and reinstalled the `drakvuf` binary. Those warnings were gone and also I could see `Running in PV context on Xen V4.15` this time.

But ig, I still have some issues, `xl list` command is hung up now. I even tried installing v0.15.0 version drakvuf binary but it also is stuck. Any idea on what the issue might be?

<details>
<summary>stuck like this</summary>

```
user@debian:/usr/lib$ sudo xl list
Name                                        ID   Mem VCPUs      State   Time(s)

```

</details

**Comment by manorit2001** [comment]
Installing the bundle again after these steps worked
- some leftover cleanup in `/usr/local` using
```
find . -name "*xen*" | xargs rm -r
```
- from xen build directory
```
make uninstall
```
- and purging using
```
apt purge drakvuf-bundle
```

I am closing this issue as it will arise mostly in development scenarios. Thanks for your helps!
