### ISSUE TITLE
[Troubleshooting] Setup and Drakvuf Test

### ISSUE THREAD

**Issue by criptk** [CERT-Polska/drakvuf-sandbox#603]
Running Ubuntu Focal 20.04 and installed the following .deb packages 
debian_buster_drakvuf-bundle-0.8-git20210614144607+fe5d189-1-generic.deb  ubuntu_focal_drakrun_0.17.0_amd64.deb
ubuntu_focal_drakcore_0.17.0_amd64.deb                                    ubuntu_focal_xen-hypervisor-4.15.0-generic-am

Running drakvuf test gives me 👍 
[2021-08-02 20:07:36,086][INFO] Checking xen-detect...
Running in PV context on Xen V4.15.
[2021-08-02 20:07:36,095][INFO] Testing if xl tool is sane...
[2021-08-02 20:07:36,115][INFO] Testing your Xen installation...
[2021-08-02 20:07:36,116][INFO] Checking if the test domain already exists...
[2021-08-02 20:07:36,124][INFO] Creating new test domain...
[2021-08-02 20:07:36,124][INFO] Creating VM test-hvm64-example
[2021-08-02 20:07:36,193][INFO] Testing altp2m feature...
/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/tools/test-altp2m: error while loading shared libraries: libjson-c.so.3: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/draksetup.py", line 275, in perform_xtf
    subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/tools/test-altp2m', 'test-hvm64-example']' returned non-zero exit status 127.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/draksetup", line 5, in <module>
    ds.main()
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/draksetup.py", line 315, in test
    if not sanity_check():
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/draksetup.py", line 241, in sanity_check
    if not perform_xtf():
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/draksetup.py", line 281, in perform_xtf
    output = e.output.decode("utf-8", "replace")
AttributeError: 'NoneType' object has no attribute 'decode'

Any pointers on to what happened ? Trying to follow (https://drakvuf-sandbox.readthedocs.io/en/latest/usage/getting_started.html)

**Comment by chivay** [comment]
Hi,

>Running Ubuntu Focal 20.04 and installed the following .deb packages
debian_buster_drakvuf-bundle-0.8-git20210614144607+fe5d189-1-generic.deb ubuntu_focal_drakrun_0.17.0_amd64.deb
ubuntu_focal_drakcore_0.17.0_amd64.deb ubuntu_focal_xen-hypervisor-4.15.0-generic-am

Please try installing `ubuntu_focal_drakvuf-bundle-0.8-git20210714133600+095a35f-1-generic.deb` instead. Debian has slightly different package versions which may be incompatible with Ubuntu.

Moreover, I'm not sure what do you mean by `ubuntu_focal_xen-hypervisor-4.15.0-generic-am`. Is it a system package? I would recommend removing it, drakvuf-bundle already contains both DRAKVUF and Xen.

**Comment by criptk** [comment]
It was this one  ubuntu_focal_xen-hypervisor-4.15.0-generic-amd64.deb

**Comment by criptk** [comment]
Did it and now this is happening
drakvuf: error while loading shared libraries: libxenctrl.so.4.14: cannot open shared object file: No such file or directory

**Comment by chivay** [comment]
Does the issue still persist? Installing packages for appropriate distro should be enough to fix this :thinking:

**Comment by criptk** [comment]
yes i had it working

**Comment by chivay** [comment]
OK. Closing.
