### ISSUE TITLE
Xubuntu 18.04 compatibility: missing dataclasses package

### ISSUE THREAD

**Issue by icedevml** [CERT-Polska/drakvuf-sandbox#64]
In Xubuntu 18.04, there is a problem with drakcore UI caused by lack of `dataclasses` module (builtin since Python 3.7, but Xubuntu has Python 3.6).

This is not on our list of officially supported systems but if this is an only issue and it is related just to the compatibility with Python 3.6 then we could probably study the topic.

```
Apr 28 16:52:46 ubuntu uwsgi[3909]: Traceback (most recent call last): Apr 28 16:52:46 ubuntu uwsgi[3909]:   File "/opt/venvs/drakcore/lib/python3.6/site-packages/drakcore/app.py", line 16, in <module> Apr 28 16:52:46 ubuntu uwsgi[3909]:     from drakcore.pstree import generate_process_tree Apr 28 16:52:46 ubuntu uwsgi[3909]:   File "/opt/venvs/drakcore/lib/python3.6/site-packages/drakcore/pstree.py", line 2, in <module> Apr 28 16:52:46 ubuntu uwsgi[3909]:     from dataclasses import dataclass, field Apr 28 16:52:46 ubuntu uwsgi[3909]: ModuleNotFoundError: No module named 'dataclasses'
```

**Comment by icedevml** [comment]
Wait, it `Pre-Depends: dpkg (>= 1.16.1),  python3.7, libpython3.7`. How come it actually ran with Python 3.6 :thinking:

**Comment by icedevml** [comment]
@chivay
