### ISSUE TITLE
Fresh install results in minio error: The specified bucket does not exist.

### ISSUE THREAD

**Issue by tklengyel** [CERT-Polska/drakvuf-sandbox#648]
After a fresh install following https://drakvuf-sandbox.readthedocs.io/en/latest/usage/getting_started.html#basic-installation I get a 500 Internal Server error trying to access the port 6300. ` journalctl -e -u drak-web.service` shows:

```
Oct 17 14:05:21 t2 uwsgi[1867]: [2021-10-17 14:05:21,337] ERROR in app: Exception on / [GET]
Oct 17 14:05:21 t2 uwsgi[1867]: Traceback (most recent call last):
Oct 17 14:05:21 t2 uwsgi[1867]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
Oct 17 14:05:21 t2 uwsgi[1867]:     response = self.full_dispatch_request()
Oct 17 14:05:21 t2 uwsgi[1867]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/flask/app.py", line 1944, in full_dispatch_request
Oct 17 14:05:21 t2 uwsgi[1867]:     self.try_trigger_before_first_request_functions()
Oct 17 14:05:21 t2 uwsgi[1867]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/flask/app.py", line 1992, in try_trigger_before_first_request_functions
Oct 17 14:05:21 t2 uwsgi[1867]:     func()
Oct 17 14:05:21 t2 uwsgi[1867]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/app.py", line 33, in update_metadata_cache
Oct 17 14:05:21 t2 uwsgi[1867]:     for analysis in AnalysisProxy(minio, None).enumerate():
Oct 17 14:05:21 t2 uwsgi[1867]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/minio/api.py", line 1039, in list_objects_v2
Oct 17 14:05:21 t2 uwsgi[1867]:     response = self._url_open(method='GET',
Oct 17 14:05:21 t2 uwsgi[1867]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/minio/api.py", line 1922, in _url_open
Oct 17 14:05:21 t2 uwsgi[1867]:     region = self._get_bucket_region(bucket_name)
Oct 17 14:05:21 t2 uwsgi[1867]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/minio/api.py", line 1852, in _get_bucket_region
Oct 17 14:05:21 t2 uwsgi[1867]:     region = self._get_bucket_location(bucket_name)
Oct 17 14:05:21 t2 uwsgi[1867]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/minio/api.py", line 1894, in _get_bucket_location
Oct 17 14:05:21 t2 uwsgi[1867]:     raise ResponseError(response, method, bucket_name).get_exception()
Oct 17 14:05:21 t2 uwsgi[1867]: minio.error.NoSuchBucket: NoSuchBucket: message: The specified bucket does not exist.
Oct 17 14:05:21 t2 uwsgi[1867]: [pid: 1867|app: 0|req: 1/3] 192.168.1.5 () {42 vars in 638 bytes} [Sun Oct 17 14:05:21 2021] GET / => generated 290 bytes in 17 msecs (HTTP/1.1 500) 4 headers in 168 bytes (1 switches on core 0)

**Comment by tklengyel** [comment]
The issue was likely because I tried to access the interface before installing the guest OS
