### ISSUE TITLE
pstree issues: Consistent post-process fails due to hard-coded Mocked parent PID

### ISSUE THREAD

**Issue by kuax** [CERT-Polska/drakvuf-sandbox#679]
Just a heads-up.

Well, I might've been lucky here... I've installed the sandbox quite a few times in the past year, and everything has always worked fine... Until this last installation, where the `drak-postprocess` consistently failed creating a process tree because of a `MultipleProcessesReturned` error. Here's a sample journald log:

```
Jan 25 09:47:55 DRAK-SBX-5 drak-postprocess[671]: [2022-01-25 09:47:55,813][INFO] Received new task - 00ffc247-4e76-4966-a562-80c999f16021
Jan 25 09:47:55 DRAK-SBX-5 drak-postprocess[671]: INFO:karton.drakrun.processor:Received new task - 00ffc247-4e76-4966-a562-80c999f16021
Jan 25 09:48:37 DRAK-SBX-5 drak-postprocess[671]: ERROR:root:Failed to parse 49 lines generated by unknown
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]: WARNING:root:Failed to process {'Plugin': 'procmon', 'TimeStamp': '1643099487.878433', 'PID': 336, 'PPID': 436, 'RunningPro>
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]: [2022-01-25 09:48:46,425][ERROR] Postprocess failed
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]: Traceback (most recent call last):
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/process.py", line 98, in process
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]:     outputs = plugin.handler(
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/postprocess/pstree.py", line 241, in build_process_tree
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]:     data = json.dumps(tree_from_log(tmp_file)).encode()
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/postprocess/pstree.py", line 235, in tree_from_log
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]:     raise e
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/postprocess/pstree.py", line 220, in tree_from_log
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]:     parse_running_process_entry(pstree, entry)
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/postprocess/pstree.py", line 127, in parse_running_process>
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]:     pstree.add_process(p)
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/postprocess/pstree.py", line 38, in add_process
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]:     raise MultipleProcessesReturned(processes)
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]: drakcore.postprocess.pstree.MultipleProcessesReturned: More than one proces fulfills condition: Mocked parent(336) []
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]: ERROR:karton.drakrun.processor:Postprocess failed
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]: Traceback (most recent call last):
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/process.py", line 98, in process
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]:     outputs = plugin.handler(
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/postprocess/pstree.py", line 241, in build_process_tree
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]:     data = json.dumps(tree_from_log(tmp_file)).encode()
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/postprocess/pstree.py", line 235, in tree_from_log
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]:     raise e
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/postprocess/pstree.py", line 220, in tree_from_log
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]:     parse_running_process_entry(pstree, entry)
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/postprocess/pstree.py", line 127, in parse_running_process>
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]:     pstree.add_process(p)
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/postprocess/pstree.py", line 38, in add_process
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]:     raise MultipleProcessesReturned(processes)
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]: drakcore.postprocess.pstree.MultipleProcessesReturned: More than one proces fulfills condition: Mocked parent(336) []
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]: [2022-01-25 09:48:46,427][INFO] Skipping generate_wireshark_key_file, missing resources
Jan 25 09:48:46 DRAK-SBX-5 drak-postprocess[671]: INFO:karton.drakrun.processor:Skipping generate_wireshark_key_file, missing resources
Jan 25 09:48:50 DRAK-SBX-5 drak-postprocess[671]: [2022-01-25 09:48:50,913][INFO] Task done - 00ffc247-4e76-4966-a562-80c999f16021
Jan 25 09:48:50 DRAK-SBX-5 drak-postprocess[671]: INFO:karton.drakrun.processor:Task done - 00ffc247-4e76-4966-a562-80c999f16021
Jan 25 09:48:51 DRAK-SBX-5 drak-postprocess[671]: [2022-01-25 09:48:50,916][INFO] Received new task - 5a8f6ae6-6b06-4e0a-98ee-d5333201f5a8
Jan 25 09:48:51 DRAK-SBX-5 drak-postprocess[671]: INFO:karton.drakrun.processor:Received new task - 5a8f6ae6-6b06-4e0a-98ee-d5333201f5a8
Jan 25 09:49:45 DRAK-SBX-5 drak-postprocess[671]: ERROR:root:Failed to parse 49 lines generated by unknown
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]: WARNING:root:Failed to process {'Plugin': 'procmon', 'TimeStamp': '1643099487.705992', 'PID': 336, 'PPID': 436, 'RunningPro>
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]: [2022-01-25 09:49:53,876][ERROR] Postprocess failed
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]: Traceback (most recent call last):
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/process.py", line 98, in process
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]:     outputs = plugin.handler(
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/postprocess/pstree.py", line 241, in build_process_tree
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]:     data = json.dumps(tree_from_log(tmp_file)).encode()
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/postprocess/pstree.py", line 235, in tree_from_log
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]:     raise e
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/postprocess/pstree.py", line 220, in tree_from_log
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]:     parse_running_process_entry(pstree, entry)
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/postprocess/pstree.py", line 127, in parse_running_process>
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]:     pstree.add_process(p)
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/postprocess/pstree.py", line 38, in add_process
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]:     raise MultipleProcessesReturned(processes)
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]: drakcore.postprocess.pstree.MultipleProcessesReturned: More than one proces fulfills condition: Mocked parent(336) []
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]: ERROR:karton.drakrun.processor:Postprocess failed
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]: Traceback (most recent call last):
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/process.py", line 98, in process
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]:     outputs = plugin.handler(
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/postprocess/pstree.py", line 241, in build_process_tree
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]:     data = json.dumps(tree_from_log(tmp_file)).encode()
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/postprocess/pstree.py", line 235, in tree_from_log
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]:     raise e
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/postprocess/pstree.py", line 220, in tree_from_log
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]:     parse_running_process_entry(pstree, entry)
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/postprocess/pstree.py", line 127, in parse_running_process>
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]:     pstree.add_process(p)
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]:   File "/opt/venvs/drakcore/lib/python3.8/site-packages/drakcore/postprocess/pstree.py", line 38, in add_process
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]:     raise MultipleProcessesReturned(processes)
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]: drakcore.postprocess.pstree.MultipleProcessesReturned: More than one proces fulfills condition: Mocked parent(336) []
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]: [2022-01-25 09:49:53,878][INFO] Skipping generate_wireshark_key_file, missing resources
Jan 25 09:49:53 DRAK-SBX-5 drak-postprocess[671]: INFO:karton.drakrun.processor:Skipping generate_wireshark_key_file, missing resources
Jan 25 09:49:57 DRAK-SBX-5 drak-postprocess[671]: [2022-01-25 09:49:57,198][INFO] Task done - 5a8f6ae6-6b06-4e0a-98ee-d5333201f5a8
Jan 25 09:49:57 DRAK-SBX-5 drak-postprocess[671]: INFO:karton.drakrun.processor:Task done - 5a8f6ae6-6b06-4e0a-98ee-d5333201f5a8

```

Sure enough, spinning up the VM again to check running processes, there happened to be a process with PID 336, the same as the hard-coded one for mocking a parent process in the process-tree generation code :smile: 

![Screenshot from 2022-01-25 10-09-05](https://user-images.githubusercontent.com/12098890/150953571-db8a2921-3f52-44dd-bca1-4d660f469c81.png)

Not sure if there would be a way of assigning that mocked parent PID during the postinstall, checking that there's currently no other process with it?

Anyway, just wanted to let you know about this :man_shrugging:  I fixed by rebooting the VM and checking that no process had PID 336

**Comment by psrok1** [comment]
Another thing is that PIDs are reused in Windows and are not raising monotonically like in Linux. MultipleProcessesReturned should not be an issue, it's just a bad design of post-processor.

There is also another bug: "Mocked PID" is there because procmon has problems with listing processes that are on the top of the tree and doesn't have PPID. It's a bad naming because it's not really mocked, it's just unknown because the information is missing.

On your screen from taskmgr we also don't see all processes because you've not clicked "Show processes from all users".

**Comment by psrok1** [comment]
Ok, that "Mocked PID" is not a procmon bug, it's phantom PID: https://github.com/CERT-Polska/drakvuf-sandbox/issues/938

In addition, that phantom PPID was probably reused by taskhost.exe process which wasn't correctly handled by postprocessor.

**Comment by kuax** [comment]
> Ok, that "Mocked PID" is not a procmon bug, it's phantom PID: #938
> 
> In addition, that phantom PPID was probably reused by taskhost.exe process which wasn't correctly handled by postprocessor.

yup, that's exactly what was going on. In my case, as long as the initial state of the VM (before calling the `draksetup postinstall` command) doesn't contain a process with that PID, I haven't encountered other such issues (for now 😅)

**Comment by psrok1** [comment]
I see in code that it is actually aware of PID reusing but mock for missing parent is just unnecessary, because it reserves PID for non-existing parent while existing process with that PID is actually further in the list.  It will be fixed by https://github.com/CERT-Polska/drakvuf-sandbox/pull/939
