### ISSUE TITLE
draksetup postinstall fails to extract VMI ofsets (timeout)

### ISSUE THREAD

**Issue by 778280** [CERT-Polska/drakvuf-sandbox#693]
**Describe the bug**

After having followed every single mandatory step of the basic installation of the latest version of drakvuf sandbox (0.18.1), when it's time to finalize the VM setup process by executing "draksetup postinstall", the process timeouts while trying to extract the VMI ofsets resulting in an error.

**How to reproduce**

I am running on a Ubuntu focal distro, having installed the drakvuf-bundle and using xen hypervisor as recomended.

I am using a Windows 7 x64 iso for the guest OS (https://download.microsoft.com/download/E/A/8/EA804D86-C3DF-4719-9966-6A66C9306598/7601.24214.180801-1700.win7sp1_ldr_escrow_CLIENT_HOMEPREMIUM_x64FRE_en-us.iso)

1. Install drakcore and drakrun
2. Execute `draksetup install /opt/path_to_windows.iso --vcpus 2 --memory 4096`
3. Perform manual desktop installation of the windows OS via vncviewer
4. Once the installation is done (After some resets) Execute `draksetup postinstall`

**Output from draksetup postinstall**:
carlos@carlos-ubuntu:~$ sudo draksetup postinstall
[2022-03-10 21:29:41,073][INFO] Cleaning up leftovers(if any)
[2022-03-10 21:29:41,074][INFO] Deleted /var/lib/drakrun/profiles/kernel.json
[2022-03-10 21:29:41,074][INFO] Ejecting installation CDs
[2022-03-10 21:29:41,219][INFO] Determined PDB GUID: daddb88936de450292977378f364b1101
[2022-03-10 21:29:41,220][INFO] Determined kernel filename: ntkrnlmp.pdb
[2022-03-10 21:29:41,220][INFO] Fetching PDB file...
[2022-03-10 21:29:41,223][DEBUG] Starting new HTTPS connection (1): msdl.microsoft.com:443
[2022-03-10 21:29:41,807][DEBUG] https://msdl.microsoft.com:443 "GET /download/symbols/ntkrnlmp.pdb/daddb88936de450292977378f364b1101/ntkrnlmp.pdb HTTP/1.1" 302 0
[2022-03-10 21:29:41,808][DEBUG] Starting new HTTPS connection (1): vsblobprodscussu5shard8.blob.core.windows.net:443
[2022-03-10 21:29:42,706][DEBUG] https://vsblobprodscussu5shard8.blob.core.windows.net:443 "GET /b-4712e0edc5a240eabf23330d7df68e77/157B235E603AEEF2FB6AD85175930A5E90515A4C2EF8A739D2EAA118203E98D500.blob?sv=2019-07-07&sr=b&si=1&sig=UawgPjgJh39PSzyg%2FK2y9gx08vfpvFyadOhA6JOZMBQ%3D&spr=https&se=2022-03-11T21%3A05%3A01Z&rscl=x-e2eid-1e7803de-e903429b-b1c0b035-049516eb-session-4e0a7a7f-7c754fc7-8d5fca41-fa31727b HTTP/1.1" 200 3206144
100%|██████████████████████| 3.21M/3.21M [00:01<00:00, 2.08MiB/s]
[2022-03-10 21:29:44,257][INFO] Generating profile out of PDB file...
[2022-03-10 21:29:46,846][INFO] Saving profile...
[2022-03-10 21:29:46,849][INFO] Deleted /var/lib/drakrun/profiles/ntkrnlmp.pdb
[2022-03-10 21:30:16,943][ERROR] vmi-win-offsets timed out
Traceback (most recent call last):
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/draksetup.py", line 676, in extract_vmi_offsets
    output = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1028, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1869, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/usr/lib/python3.8/subprocess.py", line 1072, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['vmi-win-offsets', '--name', 'vm-0', '--json-kernel', '/var/lib/drakrun/profiles/kernel.json']' timed out after 30 seconds
Traceback (most recent call last):
  File "/usr/bin/draksetup", line 5, in <module>
    ds.main()
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/draksetup.py", line 768, in postinstall
    vmi_offsets = extract_vmi_offsets("vm-0", kernel_profile)
  File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/draksetup.py", line 689, in extract_vmi_offsets
    raise RuntimeError("Extracting VMI offsets failed")
RuntimeError: Extracting VMI offsets failed

**Comment by 778280** [comment]
Update: I tried isntalling Drakvuf Sandbox v0.17.2 and everything seems to be working just fine.

**Comment by BonusPlay** [comment]
glad to hear that
