### ISSUE TITLE
draksetup test failed

### ISSUE THREAD

**Issue by yunwuxin123** [CERT-Polska/drakvuf-sandbox#716]
ubuntu18.04
followed the steps 
but has a bug like this

root@ubuntu : /home/fuzz/Desktop# draksetup test
[2022-04-18 00:17:58,850][ INFO] checking xen-detect.. .Running in PV context on xen v4.15.
[2022-04-18 00:17:58,866][ INFO] Testing if xl tool is sane.. .
[2022-04-18 00:17:58,905][INFO] Testing your Xen installation.. .
[2022-04-18 00:17:58,908][INF0] Checking if the test donain already exists...[2022-04-18 00:17:58,929][INF0] Creating new test domain.. .
[2022-04-18 00:17:58,929][INF0] creating VM test-hvn64-example[2022-04-18 00:17 : 58,950][DEBUG] stdout:
[2022-04-18 00:17:58,951][DEBUG]stderr:Parsing config from /tmp/tmpv40orkr4
libxl: error: libxl_create.c:676:libxl__donain_nake: donain creation fail: Invalid argument
libxl: error: libxl_create.c:1238:initiate_donain_create: cannot nake donain:3
[2022-04-18 00:17:58,952][DEBUG]returncode: 3Traceback (most recent call last) :
File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/util.py" , line 183, in try_run
sub = subprocess.run(list_args,**kwargs)
File "/usr/lib/python3.8 /subprocess.py" , line 512， in runraise calledProcessError(retcode, process.args,
subprocess.CalledProcessError: Comnand '[ 'xl ' , 'create', '-p'， '/tmp/tmpv40orkr
4']' returned non-zero exit status 3.
The above exception was the direct cause of the following exception:Traceback (most recent call last):
File "/usr/bin/draksetup", line 5, in <module>ds.main()
File " /opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py" , line 829in __call_
return self.main( *args,**kwargs)
File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py" , line 782, in main
rV = self.invoke(ctx)
File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py" , line 1259, in invoke
return _process_result(sub_ctx.cOmmand.invoke(sub_ctx))
File " /opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py" , line 1066, in invoke
return ctx.invoke(self.callback,**ctx.params)
File "/opt/venvs/drakrun/lib/python3.8/site-packages/click/core.py" , line 610, in invoke
return callback( *args,**kwargs)
File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/draksetup.py"，line 339, in test
if not sanity_check():
File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/draksetup.py"，line 265, in sanity_check
if not perform xtf():
test_hvm64.create(pause=True, timeout=30)
File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/vn.py",line 99,in create
try_run(args， f"Failed to launch VM {self.vm_name}"，**kwargs)
File "/opt/venvs/drakrun/lib/python3.8/site-packages/drakrun/util.py", line 197, in try_run
raise Exception(msg) from e
Exception : Failed to launch VM test-hvn64-example

I‘m a student and don't have enough technology to solve the problem, and I decide to use drakvuf to finish my FUZZ project.
Looking forward to your reply.

**Comment by icedevml** [comment]
Do you have Intel processor with Extended Page Tables support? Are you setting that up on a physical machine (not VM)?

This is the most common problem with running drakvuf-sandbox.

**Comment by yunwuxin123** [comment]
Thanks a lot.
Ignored the Intel processor.
The problem solved.

**Comment by icedevml** [comment]
Great, hope everything will run smoothly now! ;)

**Comment by manorit2001** [comment]
> Thanks a lot. Ignored the Intel processor. The problem solved.

You can close the issue if things work fine

**Comment by yunwuxin123** [comment]
sorry sir.
