### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Trenpax** [CERT-Polska/drakvuf-sandbox#743]
Hello, I have a problem by executing the draksetup postinstall command.

I see that the server tries to access the windows.net website, but can't connect because of an ssl certificate failure.
Now I've found a solution, that phyton doesn't check the certificate. 
The solution is to add by the requests "verify=False". (Here the link where i found it: https://stackoverflow.com/questions/51390968/python-ssl-certificate-verify-error )

But I can't find in drakvuf sandbox, where I can add that "verify=False".

Can anyone help me to find the file where I can add it? Or is the a better solution? Right now im stuck there....

The whole error ends in a ntdll error, because it needs the ssl certificate for this.

This is the error that I got:
Traceback (most recent call last):
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/urllib3/connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='vsblobprodscussu5shard34.blob.core.windows.net', port=443): Max retries exceeded with url: /b-4712e0edc5a240eabf23330d7df68e77/64CBA0505EFD62A4023CBEC0BC5210B50C6AAC7ABDAEF1A8194155590BF73FC300.blob?sv=2019-07-07&sr=b&si=1&sig=xaF4Q8cc36WmHm9Sw4D6KDbzUfz52pQXmsLZoQLkDjY%3D&spr=https&se=2022-12-02T18%3A23%3A36Z&rscl=x-e2eid-742736c0-92424599-8e5632e6-221b947d-session-157c282c-c2374efb-9778063d-ff5668dc (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/draksetup.py", line 607, in create_rekall_profile
    codeview_data["filename"], codeview_data["symstore_hash"], PROFILE_DIR
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/drakpdb.py", line 478, in fetch_pdb
    with requests.get(url, stream=True) as res:
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/requests/sessions.py", line 667, in send
    history = [resp for resp in gen]
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/requests/sessions.py", line 667, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/requests/sessions.py", line 245, in resolve_redirects
    **adapter_kwargs
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='vsblobprodscussu5shard34.blob.core.windows.net', port=443): Max retries exceeded with url: /b-4712e0edc5a240eabf23330d7df68e77/64CBA0505EFD62A4023CBEC0BC5210B50C6AAC7ABDAEF1A8194155590BF73FC300.blob?sv=2019-07-07&sr=b&si=1&sig=xaF4Q8cc36WmHm9Sw4D6KDbzUfz52pQXmsLZoQLkDjY%3D&spr=https&se=2022-12-02T18%3A23%3A36Z&rscl=x-e2eid-742736c0-92424599-8e5632e6-221b947d-session-157c282c-c2374efb-9778063d-ff5668dc (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/draksetup", line 5, in <module>
    ds.main()
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/draksetup.py", line 817, in postinstall
    create_missing_profiles()
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/draksetup.py", line 864, in create_missing_profiles
    create_rekall_profile(injector, profile, True)
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/draksetup.py", line 650, in create_rekall_profile
    e,
  File "/opt/venvs/drakrun/lib/python3.7/site-packages/drakrun/draksetup.py", line 570, in on_create_rekall_profile_failure
    raise Exception(f"[REQUIRED DLL] {msg}") from exception
Exception: [REQUIRED DLL] Unexpected exception while creating rekall profile for Windows/SysWOW64/ntdll.dll

**Comment by BonusPlay** [comment]
Well, you are being MITM-ed. You may want to be interested in who does that and why.

**Comment by Trenpax** [comment]
So you mean, that a device in my network has a invalid certificate, which will be rejected by windows.net right? 
It can't be the microsoft.net server, because otherwise drakvuf couldn't be installed anywhere, right?

My theory is, that the self generated certificate by my server occured the problem, but I can't find it.
Is it possible that my certificate must be replaced with antoher certificate?
