### ISSUE TITLE
Web interface: Bucket (minio) unavailable after install

### ISSUE THREAD

**Issue by andrisr223** [CERT-Polska/drakvuf-sandbox#899]
**Describe the bug**

After building and installing the sandbox, web interface at http://localhost:6300 is not available, gives internal server error; minio bucket missing. I am missing an install step. Is there a way to set up the minio bucket manually?

**How to reproduce**

    Build and install sandbox per instructions on https://drakvuf-sandbox.readthedocs.io/en/latest/usage/getting_started.html and https://drakvuf-sandbox.readthedocs.io/en/latest/building_packages.html
        drakvuf-sandbox 1b33e75db378e58fc442aa47814b10ec7549339b
        drakvuf 643c06d9c372d9443b9fa11bc251c14ce8a07201

   Execute commands
```
draksetup test
draksetup init
draksetup install...
draksetup postinstall
```
    Visit localhost:6300

**Output of the [status checking commands](https://github.com/CERT-Polska/drakvuf-sandbox#checking-service-status)**

```
$ systemctl status drak-web.service
● drak-web.service - drak-web service
     Loaded: loaded (/lib/systemd/system/drak-web.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2024-05-29 13:13:08 UTC; 16min ago
   Main PID: 18898 (uwsgi)
      Tasks: 6 (limit: 38138)
     Memory: 38.7M
        CPU: 443ms
     CGroup: /system.slice/drak-web.service
             ├─18898 /opt/venvs/drakcore/bin/uwsgi --ini /etc/drakcore/uwsgi.ini
             ├─18905 /opt/venvs/drakcore/bin/uwsgi --ini /etc/drakcore/uwsgi.ini
             ├─18906 /opt/venvs/drakcore/bin/uwsgi --ini /etc/drakcore/uwsgi.ini
             ├─18907 /opt/venvs/drakcore/bin/uwsgi --ini /etc/drakcore/uwsgi.ini
             ├─18908 /opt/venvs/drakcore/bin/uwsgi --ini /etc/drakcore/uwsgi.ini
             └─18909 /opt/venvs/drakcore/bin/uwsgi --ini /etc/drakcore/uwsgi.ini

May 29 13:15:32 drakvufbox uwsgi[18908]:   File "/opt/venvs/drakcore/lib/python3.11/site-packages/minio/api.py", line 1922, in _url_open
May 29 13:15:32 drakvufbox uwsgi[18908]:     region = self._get_bucket_region(bucket_name)
May 29 13:15:32 drakvufbox uwsgi[18908]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 29 13:15:32 drakvufbox uwsgi[18908]:   File "/opt/venvs/drakcore/lib/python3.11/site-packages/minio/api.py", line 1852, in _get_bucket_region
May 29 13:15:32 drakvufbox uwsgi[18908]:     region = self._get_bucket_location(bucket_name)
May 29 13:15:32 drakvufbox uwsgi[18908]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 29 13:15:32 drakvufbox uwsgi[18908]:   File "/opt/venvs/drakcore/lib/python3.11/site-packages/minio/api.py", line 1894, in _get_bucket_location
May 29 13:15:32 drakvufbox uwsgi[18908]:     raise ResponseError(response, method, bucket_name).get_exception()
May 29 13:15:32 drakvufbox uwsgi[18908]: minio.error.NoSuchBucket: NoSuchBucket: message: The specified bucket does not exist.
May 29 13:15:32 drakvufbox uwsgi[18908]: [pid: 18908|app: 0|req: 2/2]  () {40 vars in 613 bytes} [Wed May 29 13:15:32 2024] GET / => generated 265 bytes in 3 msecs (HTTP/1.1 500>
```

```
$ journalctl
...
May 29 13:13:18 drakvufbox uwsgi[18908]: [2024-05-29 13:13:18,418] ERROR in app: Exception on / [GET]
May 29 13:13:18 drakvufbox uwsgi[18908]: Traceback (most recent call last):
May 29 13:13:18 drakvufbox uwsgi[18908]:   File "/opt/venvs/drakcore/lib/python3.11/site-packages/flask/app.py", line 2529, in wsgi_app
May 29 13:13:18 drakvufbox uwsgi[18908]:     response = self.full_dispatch_request()
May 29 13:13:18 drakvufbox uwsgi[18908]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 29 13:13:18 drakvufbox uwsgi[18908]:   File "/opt/venvs/drakcore/lib/python3.11/site-packages/flask/app.py", line 1815, in full_dispatch_request
May 29 13:13:18 drakvufbox uwsgi[18908]:     self.ensure_sync(func)()
May 29 13:13:18 drakvufbox uwsgi[18908]:   File "/opt/venvs/drakcore/lib/python3.11/site-packages/drakcore/app.py", line 32, in update_metadata_cache
May 29 13:13:18 drakvufbox uwsgi[18908]:     for analysis in AnalysisProxy(minio, None).enumerate():
May 29 13:13:18 drakvufbox uwsgi[18908]:   File "/opt/venvs/drakcore/lib/python3.11/site-packages/minio/api.py", line 1039, in list_objects_v2
May 29 13:13:18 drakvufbox uwsgi[18908]:     response = self._url_open(method='GET',
May 29 13:13:18 drakvufbox uwsgi[18908]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 29 13:13:18 drakvufbox uwsgi[18908]:   File "/opt/venvs/drakcore/lib/python3.11/site-packages/minio/api.py", line 1922, in _url_open
May 29 13:13:18 drakvufbox uwsgi[18908]:     region = self._get_bucket_region(bucket_name)
May 29 13:13:18 drakvufbox uwsgi[18908]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 29 13:13:18 drakvufbox uwsgi[18908]:   File "/opt/venvs/drakcore/lib/python3.11/site-packages/minio/api.py", line 1852, in _get_bucket_region
May 29 13:13:18 drakvufbox uwsgi[18908]:     region = self._get_bucket_location(bucket_name)
May 29 13:13:18 drakvufbox uwsgi[18908]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 29 13:13:18 drakvufbox uwsgi[18908]:   File "/opt/venvs/drakcore/lib/python3.11/site-packages/minio/api.py", line 1894, in _get_bucket_location
May 29 13:13:18 drakvufbox uwsgi[18908]:     raise ResponseError(response, method, bucket_name).get_exception()
May 29 13:13:18 drakvufbox uwsgi[18908]: minio.error.NoSuchBucket: NoSuchBucket: message: The specified bucket does not exist.
May 29 13:13:18 drakvufbox uwsgi[18908]: [pid: 18908|app: 0|req: 1/1]  () {40 vars in 613 bytes} [Wed May 29 13:13:18 2024] GET / => generated 265 bytes in 20 msecs (HTTP/1.1 500) 4 headers in 168 bytes (1 switches on core 0)
...
```

```
$ drak-config-setup
MinIO environment file already exists, skipping...
```

```
$ tree /var/lib/drakcore
/var/lib/drakcore
├── drakcore.db
└── minio
```

```
$ uname -a
Linux  6.5.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May  7 09:00:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by andrisr223** [comment]
Running drak-system manually seems to help (minio access key and secret key also needed to be copied to /etc/drakrun/config.ini, just for safety, added to /etc/drakcore/config.ini as well)

```
$ /opt/venvs/drakcore/bin/drak-system
[2024-05-29 14:19:48,700][INFO] Verifying bucket existence...
/opt/venvs/drakcore/lib/python3.11/site-packages/karton/core/logger.py:59: UserWarning: There is no active log consumer to receive logged messages.
  warnings.warn("There is no active log consumer to receive logged messages.")
[2024-05-29 14:19:48,702][INFO] Bucket karton is missing. Creating new one...
[2024-05-29 14:19:48,704][INFO] Manager karton.system started
```
