### ISSUE TITLE
Fail analysing samples 

### ISSUE THREAD

**Issue by julie-nga** [CERT-Polska/drakvuf-sandbox#985]
**Describe the bug**

Hello, 
I followed the setup for [drakvuf-sandbox](https://drakvuf-sandbox.readthedocs.io/en/latest/usage/getting_started.html). Until step 16 everything works but at step 16 (`Test your installation by navigating to the web interface ( http://localhost:6300/ ) and uploading some samples. The default analysis time is 10 minutes.`), I have analysis crashes (I tried uploading calc.exe and notepad.exe as samples) :
![image](https://github.com/user-attachments/assets/7bceede4-3de9-4460-8a50-26a7d2951c29)

In the report I have : 
![image](https://github.com/user-attachments/assets/06a6ac84-e6fd-40f5-a79a-5fa4fa97357a)

When I click on drakrun, I have a lot of errors : 

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ju/Downloads/venv/lib/python3.9/site-packages/drakrun/main.py", line 333, in process_task
    analysis_metadata = analyze_sample(analysis_options)
  File "/home/ju/Downloads/venv/lib/python3.9/site-packages/drakrun/analyzer.py", line 295, in analyze_sample
    with run_vm(vm, options) as vm:
  File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/home/ju/Downloads/venv/lib/python3.9/site-packages/drakrun/analyzer.py", line 130, in run_vm
    vm.vm.restore()
  File "/home/ju/Downloads/venv/lib/python3.9/site-packages/drakrun/lib/vm.py", line 126, in restore
    xen_restore_vm(self.vm_name, self._cfg_path, snapshot_path, pause=pause)
  File "/home/ju/Downloads/venv/lib/python3.9/site-packages/drakrun/lib/bindings/xen.py", line 57, in xen_restore_vm
    raise RuntimeError(f"Failed to restore VM {vm_name}")
RuntimeError: Failed to restore VM vm-1
Trying to analyze sample (attempt 3/3)
Analysis attempt failed. Retrying...
Traceback (most recent call last):
  File "/home/ju/Downloads/venv/lib/python3.9/site-packages/drakrun/lib/bindings/xen.py", line 52, in xen_restore_vm
    subprocess.run(
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['xl', 'restore', PosixPath('/etc/drakrun/configs/vm-1.cfg'), PosixPath('/var/lib/drakrun/volumes/snapshot.sav')]' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ju/Downloads/venv/lib/python3.9/site-packages/drakrun/main.py", line 333, in process_task
    analysis_metadata = analyze_sample(analysis_options)
  File "/home/ju/Downloads/venv/lib/python3.9/site-packages/drakrun/analyzer.py", line 295, in analyze_sample
    with run_vm(vm, options) as vm:
  File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/home/ju/Downloads/venv/lib/python3.9/site-packages/drakrun/analyzer.py", line 130, in run_vm
    vm.vm.restore()
  File "/home/ju/Downloads/venv/lib/python3.9/site-packages/drakrun/lib/vm.py", line 126, in restore
    xen_restore_vm(self.vm_name, self._cfg_path, snapshot_path, pause=pause)
  File "/home/ju/Downloads/venv/lib/python3.9/site-packages/drakrun/lib/bindings/xen.py", line 57, in xen_restore_vm
    raise RuntimeError(f"Failed to restore VM {vm_name}")
RuntimeError: Failed to restore VM vm-1

```

My guest VM (Windows 7) works as expected. I don't understand what could be wrong. 
What could I do to make it work?

**_Setup_**
**Host OS:** Windows 11
**Host VM:** Debian 11
**Virtualization of Host VM:** with VMware Workstation
**Guest VM:** Windows 7
**Drakvuf:** [DRAKVUF Sandbox v0.19.0-alpha1](https://github.com/CERT-Polska/drakvuf-sandbox/releases/tag/v0.19.0-alpha1)

**Comment by psrok1** [comment]
I see in other issues that you've already moved forward, but I would leave some notes for the future - when VM fails to restore, useful logs in Xen are usually in `/var/log/xen` directory. In your case that would be `qemu-dm-vm-1.log` or `xl-vm-0.log`.

**Comment by julie-nga** [comment]
> I see in other issues that you've already moved forward, but I would leave some notes for the future - when VM fails to restore, useful logs in Xen are usually in `/var/log/xen` directory. In your case that would be `qemu-dm-vm-1.log` or `xl-vm-0.log`.

Noted, thanks!
